// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type BuildHistoryStatus string

const (
	BuildHistoryStatusPending   BuildHistoryStatus = "pending"
	BuildHistoryStatusRunning   BuildHistoryStatus = "running"
	BuildHistoryStatusSuccess   BuildHistoryStatus = "success"
	BuildHistoryStatusFailed    BuildHistoryStatus = "failed"
	BuildHistoryStatusCancelled BuildHistoryStatus = "cancelled"
)

func (e *BuildHistoryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BuildHistoryStatus(s)
	case string:
		*e = BuildHistoryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BuildHistoryStatus: %T", src)
	}
	return nil
}

type NullBuildHistoryStatus struct {
	BuildHistoryStatus BuildHistoryStatus `json:"build_history_status"`
	Valid              bool               `json:"valid"` // Valid is true if BuildHistoryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBuildHistoryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BuildHistoryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BuildHistoryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBuildHistoryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BuildHistoryStatus), nil
}

type DeploymentsStatus string

const (
	DeploymentsStatusPending   DeploymentsStatus = "pending"
	DeploymentsStatusRunning   DeploymentsStatus = "running"
	DeploymentsStatusSuccess   DeploymentsStatus = "success"
	DeploymentsStatusFailed    DeploymentsStatus = "failed"
	DeploymentsStatusCancelled DeploymentsStatus = "cancelled"
)

func (e *DeploymentsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeploymentsStatus(s)
	case string:
		*e = DeploymentsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeploymentsStatus: %T", src)
	}
	return nil
}

type NullDeploymentsStatus struct {
	DeploymentsStatus DeploymentsStatus `json:"deployments_status"`
	Valid             bool              `json:"valid"` // Valid is true if DeploymentsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeploymentsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeploymentsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeploymentsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeploymentsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeploymentsStatus), nil
}

type NetworksType string

const (
	NetworksTypeTcp  NetworksType = "tcp"
	NetworksTypeUdp  NetworksType = "udp"
	NetworksTypeHttp NetworksType = "http"
)

func (e *NetworksType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NetworksType(s)
	case string:
		*e = NetworksType(s)
	default:
		return fmt.Errorf("unsupported scan type for NetworksType: %T", src)
	}
	return nil
}

type NullNetworksType struct {
	NetworksType NetworksType `json:"networks_type"`
	Valid        bool         `json:"valid"` // Valid is true if NetworksType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNetworksType) Scan(value interface{}) error {
	if value == nil {
		ns.NetworksType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NetworksType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNetworksType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NetworksType), nil
}

type ProjectUserRole string

const (
	ProjectUserRoleOwner  ProjectUserRole = "owner"
	ProjectUserRoleMember ProjectUserRole = "member"
	ProjectUserRoleGuest  ProjectUserRole = "guest"
)

func (e *ProjectUserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProjectUserRole(s)
	case string:
		*e = ProjectUserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for ProjectUserRole: %T", src)
	}
	return nil
}

type NullProjectUserRole struct {
	ProjectUserRole ProjectUserRole `json:"project_user_role"`
	Valid           bool            `json:"valid"` // Valid is true if ProjectUserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProjectUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.ProjectUserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProjectUserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProjectUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProjectUserRole), nil
}

type ProjectsStatus string

const (
	ProjectsStatusActive    ProjectsStatus = "active"
	ProjectsStatusInactive  ProjectsStatus = "inactive"
	ProjectsStatusSuspended ProjectsStatus = "suspended"
	ProjectsStatusPending   ProjectsStatus = "pending"
)

func (e *ProjectsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProjectsStatus(s)
	case string:
		*e = ProjectsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProjectsStatus: %T", src)
	}
	return nil
}

type NullProjectsStatus struct {
	ProjectsStatus ProjectsStatus `json:"projects_status"`
	Valid          bool           `json:"valid"` // Valid is true if ProjectsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProjectsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProjectsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProjectsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProjectsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProjectsStatus), nil
}

type TemplatesStatus string

const (
	TemplatesStatusActive     TemplatesStatus = "active"
	TemplatesStatusInactive   TemplatesStatus = "inactive"
	TemplatesStatusDeprecated TemplatesStatus = "deprecated"
)

func (e *TemplatesStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TemplatesStatus(s)
	case string:
		*e = TemplatesStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TemplatesStatus: %T", src)
	}
	return nil
}

type NullTemplatesStatus struct {
	TemplatesStatus TemplatesStatus `json:"templates_status"`
	Valid           bool            `json:"valid"` // Valid is true if TemplatesStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTemplatesStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TemplatesStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TemplatesStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTemplatesStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TemplatesStatus), nil
}

type UsersStatus string

const (
	UsersStatusActive    UsersStatus = "active"
	UsersStatusInactive  UsersStatus = "inactive"
	UsersStatusSuspended UsersStatus = "suspended"
	UsersStatusPending   UsersStatus = "pending"
)

func (e *UsersStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersStatus(s)
	case string:
		*e = UsersStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersStatus: %T", src)
	}
	return nil
}

type NullUsersStatus struct {
	UsersStatus UsersStatus `json:"users_status"`
	Valid       bool        `json:"valid"` // Valid is true if UsersStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UsersStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersStatus), nil
}

type BuildHistory struct {
	BuildHistoryID uint32             `json:"build_history_id"`
	ContainerID    uint32             `json:"container_id"`
	Status         BuildHistoryStatus `json:"status"`
	Summary        sql.NullString     `json:"summary"`
	TektonRef      sql.NullString     `json:"tekton_ref"`
	GitCommitHash  sql.NullString     `json:"git_commit_hash"`
	CreatedAt      time.Time          `json:"created_at"`
	StartedAt      sql.NullTime       `json:"started_at"`
	FinishedAt     sql.NullTime       `json:"finished_at"`
}

type Container struct {
	ContainerID            uint32          `json:"container_id"`
	ProjectID              uint32          `json:"project_id"`
	TemplateID             sql.NullInt32   `json:"template_id"`
	Name                   string          `json:"name"`
	Slug                   string          `json:"slug"`
	Fqdn                   sql.NullString  `json:"fqdn"`
	StableWindow           sql.NullInt32   `json:"stable_window"`
	TemplateConfig         json.RawMessage `json:"template_config"`
	GitRepositoryUrl       sql.NullString  `json:"git_repository_url"`
	GitBranch              sql.NullString  `json:"git_branch"`
	GitCommitHash          sql.NullString  `json:"git_commit_hash"`
	GitDirectoryPath       sql.NullString  `json:"git_directory_path"`
	LastBuiltGitCommitHash sql.NullString  `json:"last_built_git_commit_hash"`
	CpuLimit               sql.NullInt32   `json:"cpu_limit"`
	MemoryLimit            sql.NullInt32   `json:"memory_limit"`
	MonthlyBuildTime       sql.NullInt32   `json:"monthly_build_time"`
	MonthlyBuildCount      sql.NullInt32   `json:"monthly_build_count"`
	MonthlyUptime          sql.NullString  `json:"monthly_uptime"`
	CreatedAt              time.Time       `json:"created_at"`
	UpdatedAt              sql.NullTime    `json:"updated_at"`
	DeletedAt              sql.NullTime    `json:"deleted_at"`
	IsDeleted              bool            `json:"is_deleted"`
}

type Deployment struct {
	DeploymentID uint32            `json:"deployment_id"`
	ProjectID    uint32            `json:"project_id"`
	Status       DeploymentsStatus `json:"status"`
	Summary      sql.NullString    `json:"summary"`
	TektonRef    sql.NullString    `json:"tekton_ref"`
	CreatedAt    time.Time         `json:"created_at"`
	StartedAt    sql.NullTime      `json:"started_at"`
	FinishedAt   sql.NullTime      `json:"finished_at"`
}

type EnvVar struct {
	EnvVarID    uint32         `json:"env_var_id"`
	ContainerID uint32         `json:"container_id"`
	Key         string         `json:"key"`
	Value       sql.NullString `json:"value"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Mount struct {
	ContainerID uint32       `json:"container_id"`
	VolumeID    uint32       `json:"volume_id"`
	MountPath   string       `json:"mount_path"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

type Network struct {
	NetworkID    uint32         `json:"network_id"`
	ContainerID  uint32         `json:"container_id"`
	ExternalIp   sql.NullString `json:"external_ip"`
	ExternalPort sql.NullInt16  `json:"external_port"`
	InternalPort sql.NullInt16  `json:"internal_port"`
	Type         NetworksType   `json:"type"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type Project struct {
	ProjectID    uint32         `json:"project_id"`
	Name         string         `json:"name"`
	Slug         string         `json:"slug"`
	Fqdn         sql.NullString `json:"fqdn"`
	Status       ProjectsStatus `json:"status"`
	Plan         sql.NullString `json:"plan"`
	CpuLimit     sql.NullInt32  `json:"cpu_limit"`
	MemoryLimit  sql.NullInt32  `json:"memory_limit"`
	DiskLimit    sql.NullInt32  `json:"disk_limit"`
	TrafficLimit sql.NullInt64  `json:"traffic_limit"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
	IsDeleted    bool           `json:"is_deleted"`
}

type ProjectUser struct {
	ProjectUserID uint32          `json:"project_user_id"`
	ProjectID     uint32          `json:"project_id"`
	UserID        uint32          `json:"user_id"`
	Role          ProjectUserRole `json:"role"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     sql.NullTime    `json:"updated_at"`
	DeletedAt     sql.NullTime    `json:"deleted_at"`
	IsDeleted     bool            `json:"is_deleted"`
}

type Secret struct {
	SecretID    uint32       `json:"secret_id"`
	ContainerID uint32       `json:"container_id"`
	Key         string       `json:"key"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

type Template struct {
	TemplateID     uint32          `json:"template_id"`
	Name           string          `json:"name"`
	TemplateBody   sql.NullString  `json:"template_body"`
	TemplateConfig json.RawMessage `json:"template_config"`
	Status         TemplatesStatus `json:"status"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      sql.NullTime    `json:"updated_at"`
}

type User struct {
	UserID            uint32         `json:"user_id"`
	Username          string         `json:"username"`
	PasswordHash      string         `json:"password_hash"`
	PasswordUpdatedAt sql.NullTime   `json:"password_updated_at"`
	Name              sql.NullString `json:"name"`
	Email             string         `json:"email"`
	Phone             sql.NullString `json:"phone"`
	Status            UsersStatus    `json:"status"`
	Organization      sql.NullString `json:"organization"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
	DeletedAt         sql.NullTime   `json:"deleted_at"`
	IsDeleted         bool           `json:"is_deleted"`
}

type Volume struct {
	VolumeID  uint32       `json:"volume_id"`
	ProjectID uint32       `json:"project_id"`
	Name      string       `json:"name"`
	Capacity  uint32       `json:"capacity"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
