-- Rollback consolidated schema - Drop all tables
-- Version: 2.0.0

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `PROJECT_USER`;
DROP TABLE IF EXISTS `OAUTH_STATES`;
DROP TABLE IF EXISTS `verification_tokens`;
DROP TABLE IF EXISTS `BUILD_HISTORY`;
DROP TABLE IF EXISTS `BUILD_VARS`;
DROP TABLE IF EXISTS `SECRETS`;
DROP TABLE IF EXISTS `NETWORKS`;
DROP TABLE IF EXISTS `ENV_VARS`;
DROP TABLE IF EXISTS `MOUNTS`;
DROP TABLE IF EXISTS `CONTAINERS`;
DROP TABLE IF EXISTS `GITHUB_INSTALLATIONS`;
DROP TABLE IF EXISTS `VOLUMES`;
DROP TABLE IF EXISTS `DEPLOYMENTS`;
DROP TABLE IF EXISTS `PROJECTS`;
DROP TABLE IF EXISTS `TEMPLATES`;
DROP TABLE IF EXISTS `SYSTEM_SETTINGS`;
DROP TABLE IF EXISTS `USERS`;

SET FOREIGN_KEY_CHECKS = 1;
