-- Rollback script for initial schema migration
-- This will remove all tables created in the up migration

-- Drop tables in reverse order of dependencies
DROP TABLE IF EXISTS `PROJECT_USER`;
DROP TABLE IF EXISTS `MOUNTS`;
DROP TABLE IF EXISTS `SECRETS`;
DROP TABLE IF EXISTS `BUILD_HISTORY`;
DROP TABLE IF EXISTS `NETWORKS`;
DROP TABLE IF EXISTS `ENV_VARS`;
DROP TABLE IF EXISTS `DEPLOYMENTS`;
DROP TABLE IF EXISTS `CONTAINERS`;
DROP TABLE IF EXISTS `VOLUMES`;
DROP TABLE IF EXISTS `TEMPLATES`;
DROP TABLE IF EXISTS `PROJECTS`;
DROP TABLE IF EXISTS `USERS`;
