// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: incidents.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createIncident = `-- name: CreateIncident :execresult
INSERT INTO SERVICE_INCIDENTS (
    service_name,
    severity,
    title,
    description,
    status,
    started_at,
    affected_services
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateIncidentParams struct {
	ServiceName      string                   `json:"service_name"`
	Severity         ServiceIncidentsSeverity `json:"severity"`
	Title            string                   `json:"title"`
	Description      sql.NullString           `json:"description"`
	Status           ServiceIncidentsStatus   `json:"status"`
	StartedAt        time.Time                `json:"started_at"`
	AffectedServices json.RawMessage          `json:"affected_services"`
}

func (q *Queries) CreateIncident(ctx context.Context, arg CreateIncidentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createIncident,
		arg.ServiceName,
		arg.Severity,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.StartedAt,
		arg.AffectedServices,
	)
}

const getActiveIncidents = `-- name: GetActiveIncidents :many
SELECT incident_id, service_name, severity, title, description, status, started_at, resolved_at, duration_minutes, affected_services, created_at, updated_at FROM SERVICE_INCIDENTS
WHERE status != 'resolved'
ORDER BY started_at DESC
`

func (q *Queries) GetActiveIncidents(ctx context.Context) ([]ServiceIncident, error) {
	rows, err := q.db.QueryContext(ctx, getActiveIncidents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceIncident{}
	for rows.Next() {
		var i ServiceIncident
		if err := rows.Scan(
			&i.IncidentID,
			&i.ServiceName,
			&i.Severity,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.StartedAt,
			&i.ResolvedAt,
			&i.DurationMinutes,
			&i.AffectedServices,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIncidentByID = `-- name: GetIncidentByID :one
SELECT incident_id, service_name, severity, title, description, status, started_at, resolved_at, duration_minutes, affected_services, created_at, updated_at FROM SERVICE_INCIDENTS
WHERE incident_id = ?
`

func (q *Queries) GetIncidentByID(ctx context.Context, incidentID uint64) (ServiceIncident, error) {
	row := q.db.QueryRowContext(ctx, getIncidentByID, incidentID)
	var i ServiceIncident
	err := row.Scan(
		&i.IncidentID,
		&i.ServiceName,
		&i.Severity,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.DurationMinutes,
		&i.AffectedServices,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIncidentsByService = `-- name: GetIncidentsByService :many
SELECT incident_id, service_name, severity, title, description, status, started_at, resolved_at, duration_minutes, affected_services, created_at, updated_at FROM SERVICE_INCIDENTS
WHERE service_name = ?
ORDER BY started_at DESC
LIMIT ?
`

type GetIncidentsByServiceParams struct {
	ServiceName string `json:"service_name"`
	Limit       int32  `json:"limit"`
}

func (q *Queries) GetIncidentsByService(ctx context.Context, arg GetIncidentsByServiceParams) ([]ServiceIncident, error) {
	rows, err := q.db.QueryContext(ctx, getIncidentsByService, arg.ServiceName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceIncident{}
	for rows.Next() {
		var i ServiceIncident
		if err := rows.Scan(
			&i.IncidentID,
			&i.ServiceName,
			&i.Severity,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.StartedAt,
			&i.ResolvedAt,
			&i.DurationMinutes,
			&i.AffectedServices,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentIncidents = `-- name: GetRecentIncidents :many
SELECT incident_id, service_name, severity, title, description, status, started_at, resolved_at, duration_minutes, affected_services, created_at, updated_at FROM SERVICE_INCIDENTS
ORDER BY started_at DESC
LIMIT ?
`

func (q *Queries) GetRecentIncidents(ctx context.Context, limit int32) ([]ServiceIncident, error) {
	rows, err := q.db.QueryContext(ctx, getRecentIncidents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceIncident{}
	for rows.Next() {
		var i ServiceIncident
		if err := rows.Scan(
			&i.IncidentID,
			&i.ServiceName,
			&i.Severity,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.StartedAt,
			&i.ResolvedAt,
			&i.DurationMinutes,
			&i.AffectedServices,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveIncident = `-- name: ResolveIncident :exec
UPDATE SERVICE_INCIDENTS
SET
    status = 'resolved',
    resolved_at = ?,
    duration_minutes = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE incident_id = ?
`

type ResolveIncidentParams struct {
	ResolvedAt      sql.NullTime  `json:"resolved_at"`
	DurationMinutes sql.NullInt32 `json:"duration_minutes"`
	IncidentID      uint64        `json:"incident_id"`
}

func (q *Queries) ResolveIncident(ctx context.Context, arg ResolveIncidentParams) error {
	_, err := q.db.ExecContext(ctx, resolveIncident, arg.ResolvedAt, arg.DurationMinutes, arg.IncidentID)
	return err
}

const updateIncident = `-- name: UpdateIncident :exec
UPDATE SERVICE_INCIDENTS
SET
    severity = ?,
    title = ?,
    description = ?,
    status = ?,
    resolved_at = ?,
    duration_minutes = ?,
    affected_services = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE incident_id = ?
`

type UpdateIncidentParams struct {
	Severity         ServiceIncidentsSeverity `json:"severity"`
	Title            string                   `json:"title"`
	Description      sql.NullString           `json:"description"`
	Status           ServiceIncidentsStatus   `json:"status"`
	ResolvedAt       sql.NullTime             `json:"resolved_at"`
	DurationMinutes  sql.NullInt32            `json:"duration_minutes"`
	AffectedServices json.RawMessage          `json:"affected_services"`
	IncidentID       uint64                   `json:"incident_id"`
}

func (q *Queries) UpdateIncident(ctx context.Context, arg UpdateIncidentParams) error {
	_, err := q.db.ExecContext(ctx, updateIncident,
		arg.Severity,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.ResolvedAt,
		arg.DurationMinutes,
		arg.AffectedServices,
		arg.IncidentID,
	)
	return err
}
