// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	CreateIncident(ctx context.Context, arg CreateIncidentParams) (sql.Result, error)
	CreateStatusCheck(ctx context.Context, arg CreateStatusCheckParams) (sql.Result, error)
	DeleteOldStatusChecks(ctx context.Context, checkedAt time.Time) error
	GetActiveIncidents(ctx context.Context) ([]ServiceIncident, error)
	GetDailyUptimeData(ctx context.Context, arg GetDailyUptimeDataParams) ([]GetDailyUptimeDataRow, error)
	GetIncidentByID(ctx context.Context, incidentID uint64) (ServiceIncident, error)
	GetIncidentsByService(ctx context.Context, arg GetIncidentsByServiceParams) ([]ServiceIncident, error)
	GetLatestStatusCheck(ctx context.Context, serviceName string) (ServiceStatusCheck, error)
	GetLatestStatusChecks(ctx context.Context) ([]GetLatestStatusChecksRow, error)
	GetRecentIncidents(ctx context.Context, limit int32) ([]ServiceIncident, error)
	GetStatusChecksByPeriod(ctx context.Context, arg GetStatusChecksByPeriodParams) ([]ServiceStatusCheck, error)
	GetUptimeStats(ctx context.Context, arg GetUptimeStatsParams) (GetUptimeStatsRow, error)
	ResolveIncident(ctx context.Context, arg ResolveIncidentParams) error
	UpdateIncident(ctx context.Context, arg UpdateIncidentParams) error
	UpsertDailyUptime(ctx context.Context, arg UpsertDailyUptimeParams) error
}

var _ Querier = (*Queries)(nil)
