// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: status_checks.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createStatusCheck = `-- name: CreateStatusCheck :execresult
INSERT INTO SERVICE_STATUS_CHECKS (
    service_name,
    service_category,
    status,
    response_time_ms,
    error_message,
    metadata
) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateStatusCheckParams struct {
	ServiceName     string                             `json:"service_name"`
	ServiceCategory ServiceStatusChecksServiceCategory `json:"service_category"`
	Status          ServiceStatusChecksStatus          `json:"status"`
	ResponseTimeMs  sql.NullInt32                      `json:"response_time_ms"`
	ErrorMessage    sql.NullString                     `json:"error_message"`
	Metadata        json.RawMessage                    `json:"metadata"`
}

func (q *Queries) CreateStatusCheck(ctx context.Context, arg CreateStatusCheckParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createStatusCheck,
		arg.ServiceName,
		arg.ServiceCategory,
		arg.Status,
		arg.ResponseTimeMs,
		arg.ErrorMessage,
		arg.Metadata,
	)
}

const deleteOldStatusChecks = `-- name: DeleteOldStatusChecks :exec
DELETE FROM SERVICE_STATUS_CHECKS
WHERE checked_at < ?
`

func (q *Queries) DeleteOldStatusChecks(ctx context.Context, checkedAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteOldStatusChecks, checkedAt)
	return err
}

const getDailyUptimeData = `-- name: GetDailyUptimeData :many
SELECT
    date,
    uptime_percentage,
    avg_response_time_ms,
    p95_response_time_ms,
    incident_count
FROM SERVICE_UPTIME_DAILY
WHERE service_name = ?
  AND date BETWEEN ? AND ?
ORDER BY date DESC
`

type GetDailyUptimeDataParams struct {
	ServiceName string    `json:"service_name"`
	FromDate    time.Time `json:"from_date"`
	ToDate      time.Time `json:"to_date"`
}

type GetDailyUptimeDataRow struct {
	Date              time.Time     `json:"date"`
	UptimePercentage  string        `json:"uptime_percentage"`
	AvgResponseTimeMs sql.NullInt32 `json:"avg_response_time_ms"`
	P95ResponseTimeMs sql.NullInt32 `json:"p95_response_time_ms"`
	IncidentCount     uint16        `json:"incident_count"`
}

func (q *Queries) GetDailyUptimeData(ctx context.Context, arg GetDailyUptimeDataParams) ([]GetDailyUptimeDataRow, error) {
	rows, err := q.db.QueryContext(ctx, getDailyUptimeData, arg.ServiceName, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDailyUptimeDataRow{}
	for rows.Next() {
		var i GetDailyUptimeDataRow
		if err := rows.Scan(
			&i.Date,
			&i.UptimePercentage,
			&i.AvgResponseTimeMs,
			&i.P95ResponseTimeMs,
			&i.IncidentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestStatusCheck = `-- name: GetLatestStatusCheck :one
SELECT check_id, service_name, service_category, status, response_time_ms, error_message, checked_at, metadata FROM SERVICE_STATUS_CHECKS
WHERE service_name = ?
ORDER BY checked_at DESC
LIMIT 1
`

func (q *Queries) GetLatestStatusCheck(ctx context.Context, serviceName string) (ServiceStatusCheck, error) {
	row := q.db.QueryRowContext(ctx, getLatestStatusCheck, serviceName)
	var i ServiceStatusCheck
	err := row.Scan(
		&i.CheckID,
		&i.ServiceName,
		&i.ServiceCategory,
		&i.Status,
		&i.ResponseTimeMs,
		&i.ErrorMessage,
		&i.CheckedAt,
		&i.Metadata,
	)
	return i, err
}

const getLatestStatusChecks = `-- name: GetLatestStatusChecks :many
SELECT check_id, service_name, service_category, status, response_time_ms, error_message, checked_at, metadata, rn FROM (
    SELECT check_id, service_name, service_category, status, response_time_ms, error_message, checked_at, metadata,
           ROW_NUMBER() OVER (PARTITION BY service_name ORDER BY checked_at DESC) as rn
    FROM SERVICE_STATUS_CHECKS
    WHERE checked_at >= DATE_SUB(NOW(), INTERVAL 5 MINUTE)
) t
WHERE rn = 1
`

type GetLatestStatusChecksRow struct {
	CheckID         uint64                             `json:"check_id"`
	ServiceName     string                             `json:"service_name"`
	ServiceCategory ServiceStatusChecksServiceCategory `json:"service_category"`
	Status          ServiceStatusChecksStatus          `json:"status"`
	ResponseTimeMs  sql.NullInt32                      `json:"response_time_ms"`
	ErrorMessage    sql.NullString                     `json:"error_message"`
	CheckedAt       time.Time                          `json:"checked_at"`
	Metadata        json.RawMessage                    `json:"metadata"`
	Rn              interface{}                        `json:"rn"`
}

func (q *Queries) GetLatestStatusChecks(ctx context.Context) ([]GetLatestStatusChecksRow, error) {
	rows, err := q.db.QueryContext(ctx, getLatestStatusChecks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLatestStatusChecksRow{}
	for rows.Next() {
		var i GetLatestStatusChecksRow
		if err := rows.Scan(
			&i.CheckID,
			&i.ServiceName,
			&i.ServiceCategory,
			&i.Status,
			&i.ResponseTimeMs,
			&i.ErrorMessage,
			&i.CheckedAt,
			&i.Metadata,
			&i.Rn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatusChecksByPeriod = `-- name: GetStatusChecksByPeriod :many
SELECT check_id, service_name, service_category, status, response_time_ms, error_message, checked_at, metadata FROM SERVICE_STATUS_CHECKS
WHERE service_name = ?
  AND checked_at BETWEEN ? AND ?
ORDER BY checked_at DESC
`

type GetStatusChecksByPeriodParams struct {
	ServiceName   string    `json:"service_name"`
	FromCheckedAt time.Time `json:"from_checked_at"`
	ToCheckedAt   time.Time `json:"to_checked_at"`
}

func (q *Queries) GetStatusChecksByPeriod(ctx context.Context, arg GetStatusChecksByPeriodParams) ([]ServiceStatusCheck, error) {
	rows, err := q.db.QueryContext(ctx, getStatusChecksByPeriod, arg.ServiceName, arg.FromCheckedAt, arg.ToCheckedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceStatusCheck{}
	for rows.Next() {
		var i ServiceStatusCheck
		if err := rows.Scan(
			&i.CheckID,
			&i.ServiceName,
			&i.ServiceCategory,
			&i.Status,
			&i.ResponseTimeMs,
			&i.ErrorMessage,
			&i.CheckedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUptimeStats = `-- name: GetUptimeStats :one
SELECT
    COUNT(*) as total_checks,
    SUM(CASE WHEN status = 'operational' THEN 1 ELSE 0 END) as successful_checks,
    CAST(AVG(CASE WHEN response_time_ms IS NOT NULL THEN response_time_ms ELSE NULL END) AS UNSIGNED) as avg_response_time_ms
FROM SERVICE_STATUS_CHECKS
WHERE service_name = ?
  AND checked_at >= DATE_SUB(NOW(), INTERVAL ? HOUR)
`

type GetUptimeStatsParams struct {
	ServiceName string      `json:"service_name"`
	DATESUB     interface{} `json:"DATE_SUB"`
}

type GetUptimeStatsRow struct {
	TotalChecks       int64       `json:"total_checks"`
	SuccessfulChecks  interface{} `json:"successful_checks"`
	AvgResponseTimeMs int64       `json:"avg_response_time_ms"`
}

func (q *Queries) GetUptimeStats(ctx context.Context, arg GetUptimeStatsParams) (GetUptimeStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getUptimeStats, arg.ServiceName, arg.DATESUB)
	var i GetUptimeStatsRow
	err := row.Scan(&i.TotalChecks, &i.SuccessfulChecks, &i.AvgResponseTimeMs)
	return i, err
}

const upsertDailyUptime = `-- name: UpsertDailyUptime :exec
INSERT INTO SERVICE_UPTIME_DAILY (
    service_name,
    date,
    total_checks,
    successful_checks,
    uptime_percentage,
    avg_response_time_ms,
    p95_response_time_ms,
    downtime_minutes,
    incident_count
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    total_checks = VALUES(total_checks),
    successful_checks = VALUES(successful_checks),
    uptime_percentage = VALUES(uptime_percentage),
    avg_response_time_ms = VALUES(avg_response_time_ms),
    p95_response_time_ms = VALUES(p95_response_time_ms),
    downtime_minutes = VALUES(downtime_minutes),
    incident_count = VALUES(incident_count),
    updated_at = CURRENT_TIMESTAMP
`

type UpsertDailyUptimeParams struct {
	ServiceName       string        `json:"service_name"`
	Date              time.Time     `json:"date"`
	TotalChecks       uint32        `json:"total_checks"`
	SuccessfulChecks  uint32        `json:"successful_checks"`
	UptimePercentage  string        `json:"uptime_percentage"`
	AvgResponseTimeMs sql.NullInt32 `json:"avg_response_time_ms"`
	P95ResponseTimeMs sql.NullInt32 `json:"p95_response_time_ms"`
	DowntimeMinutes   uint32        `json:"downtime_minutes"`
	IncidentCount     uint16        `json:"incident_count"`
}

func (q *Queries) UpsertDailyUptime(ctx context.Context, arg UpsertDailyUptimeParams) error {
	_, err := q.db.ExecContext(ctx, upsertDailyUptime,
		arg.ServiceName,
		arg.Date,
		arg.TotalChecks,
		arg.SuccessfulChecks,
		arg.UptimePercentage,
		arg.AvgResponseTimeMs,
		arg.P95ResponseTimeMs,
		arg.DowntimeMinutes,
		arg.IncidentCount,
	)
	return err
}
