// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: build_vars.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countBuildVarsByContainerID = `-- name: CountBuildVarsByContainerID :one
SELECT COUNT(*) as total FROM BUILD_VARS WHERE container_id = ?
`

func (q *Queries) CountBuildVarsByContainerID(ctx context.Context, containerID uint32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBuildVarsByContainerID, containerID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createBuildVar = `-- name: CreateBuildVar :execresult

INSERT INTO BUILD_VARS (
    container_id, ` + "`" + `key` + "`" + `, value,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?)
`

type CreateBuildVarParams struct {
	ContainerID uint32         `json:"container_id"`
	Key         string         `json:"key"`
	Value       sql.NullString `json:"value"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

// Build Variables CRUD
func (q *Queries) CreateBuildVar(ctx context.Context, arg CreateBuildVarParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createBuildVar,
		arg.ContainerID,
		arg.Key,
		arg.Value,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const deleteBuildVar = `-- name: DeleteBuildVar :execresult
DELETE FROM BUILD_VARS
WHERE container_id = ? AND ` + "`" + `key` + "`" + ` = ?
`

type DeleteBuildVarParams struct {
	ContainerID uint32 `json:"container_id"`
	Key         string `json:"key"`
}

func (q *Queries) DeleteBuildVar(ctx context.Context, arg DeleteBuildVarParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteBuildVar, arg.ContainerID, arg.Key)
}

const deleteBuildVarsByContainerID = `-- name: DeleteBuildVarsByContainerID :execresult
DELETE FROM BUILD_VARS
WHERE container_id = ?
`

func (q *Queries) DeleteBuildVarsByContainerID(ctx context.Context, containerID uint32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteBuildVarsByContainerID, containerID)
}

const getBuildVarByKey = `-- name: GetBuildVarByKey :one
SELECT
    container_id, ` + "`" + `key` + "`" + `, value,
    created_at, updated_at, build_var_id
FROM BUILD_VARS
WHERE container_id = ? AND ` + "`" + `key` + "`" + ` = ?
`

type GetBuildVarByKeyParams struct {
	ContainerID uint32 `json:"container_id"`
	Key         string `json:"key"`
}

type GetBuildVarByKeyRow struct {
	ContainerID uint32         `json:"container_id"`
	Key         string         `json:"key"`
	Value       sql.NullString `json:"value"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	BuildVarID  uint32         `json:"build_var_id"`
}

func (q *Queries) GetBuildVarByKey(ctx context.Context, arg GetBuildVarByKeyParams) (GetBuildVarByKeyRow, error) {
	row := q.db.QueryRowContext(ctx, getBuildVarByKey, arg.ContainerID, arg.Key)
	var i GetBuildVarByKeyRow
	err := row.Scan(
		&i.ContainerID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BuildVarID,
	)
	return i, err
}

const getBuildVarsByContainerID = `-- name: GetBuildVarsByContainerID :many
SELECT
    container_id, ` + "`" + `key` + "`" + `, value,
    created_at, updated_at, build_var_id
FROM BUILD_VARS
WHERE container_id = ?
ORDER BY ` + "`" + `key` + "`" + ` ASC
`

type GetBuildVarsByContainerIDRow struct {
	ContainerID uint32         `json:"container_id"`
	Key         string         `json:"key"`
	Value       sql.NullString `json:"value"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	BuildVarID  uint32         `json:"build_var_id"`
}

func (q *Queries) GetBuildVarsByContainerID(ctx context.Context, containerID uint32) ([]GetBuildVarsByContainerIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getBuildVarsByContainerID, containerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBuildVarsByContainerIDRow{}
	for rows.Next() {
		var i GetBuildVarsByContainerIDRow
		if err := rows.Scan(
			&i.ContainerID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BuildVarID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBuildVar = `-- name: UpdateBuildVar :execresult
UPDATE BUILD_VARS SET
    value = ?,
    updated_at = ?
WHERE container_id = ? AND ` + "`" + `key` + "`" + ` = ?
`

type UpdateBuildVarParams struct {
	Value       sql.NullString `json:"value"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	ContainerID uint32         `json:"container_id"`
	Key         string         `json:"key"`
}

func (q *Queries) UpdateBuildVar(ctx context.Context, arg UpdateBuildVarParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateBuildVar,
		arg.Value,
		arg.UpdatedAt,
		arg.ContainerID,
		arg.Key,
	)
}
