// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: containers.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const countContainers = `-- name: CountContainers :one
SELECT COUNT(*) as total FROM CONTAINERS WHERE is_deleted = FALSE
`

func (q *Queries) CountContainers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countContainers)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countContainersByProjectID = `-- name: CountContainersByProjectID :one
SELECT COUNT(*) as total FROM CONTAINERS WHERE project_id = ? AND is_deleted = FALSE
`

func (q *Queries) CountContainersByProjectID(ctx context.Context, projectID uint32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countContainersByProjectID, projectID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countContainersByTemplateID = `-- name: CountContainersByTemplateID :one
SELECT COUNT(*) as total FROM CONTAINERS WHERE template_id = ? AND is_deleted = FALSE
`

func (q *Queries) CountContainersByTemplateID(ctx context.Context, templateID sql.NullInt32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countContainersByTemplateID, templateID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createContainer = `-- name: CreateContainer :execresult

INSERT INTO CONTAINERS (
    project_id, template_id, name, slug, stable_window,
    template_config, github_installation_id, git_repository_url, git_branch, git_directory_path, git_commit_hash,
    last_built_git_commit_hash, cpu_limit, memory_limit,
    monthly_build_time, monthly_build_count, monthly_uptime,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateContainerParams struct {
	ProjectID              uint32          `json:"project_id"`
	TemplateID             sql.NullInt32   `json:"template_id"`
	Name                   string          `json:"name"`
	Slug                   string          `json:"slug"`
	StableWindow           sql.NullInt32   `json:"stable_window"`
	TemplateConfig         json.RawMessage `json:"template_config"`
	GithubInstallationID   sql.NullInt64   `json:"github_installation_id"`
	GitRepositoryUrl       sql.NullString  `json:"git_repository_url"`
	GitBranch              sql.NullString  `json:"git_branch"`
	GitDirectoryPath       sql.NullString  `json:"git_directory_path"`
	GitCommitHash          sql.NullString  `json:"git_commit_hash"`
	LastBuiltGitCommitHash sql.NullString  `json:"last_built_git_commit_hash"`
	CpuLimit               sql.NullInt32   `json:"cpu_limit"`
	MemoryLimit            sql.NullInt32   `json:"memory_limit"`
	MonthlyBuildTime       sql.NullInt32   `json:"monthly_build_time"`
	MonthlyBuildCount      sql.NullInt32   `json:"monthly_build_count"`
	MonthlyUptime          sql.NullString  `json:"monthly_uptime"`
	CreatedAt              time.Time       `json:"created_at"`
	UpdatedAt              sql.NullTime    `json:"updated_at"`
}

// Containers CRUD
func (q *Queries) CreateContainer(ctx context.Context, arg CreateContainerParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createContainer,
		arg.ProjectID,
		arg.TemplateID,
		arg.Name,
		arg.Slug,
		arg.StableWindow,
		arg.TemplateConfig,
		arg.GithubInstallationID,
		arg.GitRepositoryUrl,
		arg.GitBranch,
		arg.GitDirectoryPath,
		arg.GitCommitHash,
		arg.LastBuiltGitCommitHash,
		arg.CpuLimit,
		arg.MemoryLimit,
		arg.MonthlyBuildTime,
		arg.MonthlyBuildCount,
		arg.MonthlyUptime,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const deleteContainer = `-- name: DeleteContainer :execresult
UPDATE CONTAINERS SET
    is_deleted = TRUE,
    deleted_at = ?,
    updated_at = ?
WHERE container_id = ?
`

type DeleteContainerParams struct {
	DeletedAt   sql.NullTime `json:"deleted_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
	ContainerID uint32       `json:"container_id"`
}

func (q *Queries) DeleteContainer(ctx context.Context, arg DeleteContainerParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteContainer, arg.DeletedAt, arg.UpdatedAt, arg.ContainerID)
}

const deleteContainersByProjectID = `-- name: DeleteContainersByProjectID :execresult
UPDATE CONTAINERS SET
    is_deleted = TRUE,
    deleted_at = ?,
    updated_at = ?
WHERE project_id = ?
`

type DeleteContainersByProjectIDParams struct {
	DeletedAt sql.NullTime `json:"deleted_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	ProjectID uint32       `json:"project_id"`
}

func (q *Queries) DeleteContainersByProjectID(ctx context.Context, arg DeleteContainersByProjectIDParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteContainersByProjectID, arg.DeletedAt, arg.UpdatedAt, arg.ProjectID)
}

const existsByNameAndProjectID = `-- name: ExistsByNameAndProjectID :one
SELECT EXISTS(SELECT 1 FROM CONTAINERS WHERE project_id = ? AND name = ? AND is_deleted = FALSE) as container_exists
`

type ExistsByNameAndProjectIDParams struct {
	ProjectID uint32 `json:"project_id"`
	Name      string `json:"name"`
}

func (q *Queries) ExistsByNameAndProjectID(ctx context.Context, arg ExistsByNameAndProjectIDParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsByNameAndProjectID, arg.ProjectID, arg.Name)
	var container_exists bool
	err := row.Scan(&container_exists)
	return container_exists, err
}

const existsBySlug = `-- name: ExistsBySlug :one
SELECT EXISTS(SELECT 1 FROM CONTAINERS WHERE slug = ? AND is_deleted = FALSE) as container_exists
`

func (q *Queries) ExistsBySlug(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsBySlug, slug)
	var container_exists bool
	err := row.Scan(&container_exists)
	return container_exists, err
}

const getContainerByID = `-- name: GetContainerByID :one
SELECT container_id, project_id, template_id, name, slug, stable_window, template_config, git_repository_url, git_branch, git_commit_hash, git_directory_path, last_built_git_commit_hash, cpu_limit, memory_limit, monthly_build_time, monthly_build_count, monthly_uptime, created_at, updated_at, deleted_at, is_deleted, github_installation_id
FROM CONTAINERS
WHERE container_id = ? AND is_deleted = FALSE
`

func (q *Queries) GetContainerByID(ctx context.Context, containerID uint32) (Container, error) {
	row := q.db.QueryRowContext(ctx, getContainerByID, containerID)
	var i Container
	err := row.Scan(
		&i.ContainerID,
		&i.ProjectID,
		&i.TemplateID,
		&i.Name,
		&i.Slug,
		&i.StableWindow,
		&i.TemplateConfig,
		&i.GitRepositoryUrl,
		&i.GitBranch,
		&i.GitCommitHash,
		&i.GitDirectoryPath,
		&i.LastBuiltGitCommitHash,
		&i.CpuLimit,
		&i.MemoryLimit,
		&i.MonthlyBuildTime,
		&i.MonthlyBuildCount,
		&i.MonthlyUptime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsDeleted,
		&i.GithubInstallationID,
	)
	return i, err
}

const getContainerByIDForUpdate = `-- name: GetContainerByIDForUpdate :one
SELECT container_id, project_id, template_id, name, slug, stable_window, template_config, git_repository_url, git_branch, git_commit_hash, git_directory_path, last_built_git_commit_hash, cpu_limit, memory_limit, monthly_build_time, monthly_build_count, monthly_uptime, created_at, updated_at, deleted_at, is_deleted, github_installation_id
FROM CONTAINERS
WHERE container_id = ? AND is_deleted = FALSE
FOR UPDATE
`

func (q *Queries) GetContainerByIDForUpdate(ctx context.Context, containerID uint32) (Container, error) {
	row := q.db.QueryRowContext(ctx, getContainerByIDForUpdate, containerID)
	var i Container
	err := row.Scan(
		&i.ContainerID,
		&i.ProjectID,
		&i.TemplateID,
		&i.Name,
		&i.Slug,
		&i.StableWindow,
		&i.TemplateConfig,
		&i.GitRepositoryUrl,
		&i.GitBranch,
		&i.GitCommitHash,
		&i.GitDirectoryPath,
		&i.LastBuiltGitCommitHash,
		&i.CpuLimit,
		&i.MemoryLimit,
		&i.MonthlyBuildTime,
		&i.MonthlyBuildCount,
		&i.MonthlyUptime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsDeleted,
		&i.GithubInstallationID,
	)
	return i, err
}

const getContainerBySlug = `-- name: GetContainerBySlug :one
SELECT container_id, project_id, template_id, name, slug, stable_window, template_config, git_repository_url, git_branch, git_commit_hash, git_directory_path, last_built_git_commit_hash, cpu_limit, memory_limit, monthly_build_time, monthly_build_count, monthly_uptime, created_at, updated_at, deleted_at, is_deleted, github_installation_id
FROM CONTAINERS
WHERE slug = ? AND is_deleted = FALSE
`

func (q *Queries) GetContainerBySlug(ctx context.Context, slug string) (Container, error) {
	row := q.db.QueryRowContext(ctx, getContainerBySlug, slug)
	var i Container
	err := row.Scan(
		&i.ContainerID,
		&i.ProjectID,
		&i.TemplateID,
		&i.Name,
		&i.Slug,
		&i.StableWindow,
		&i.TemplateConfig,
		&i.GitRepositoryUrl,
		&i.GitBranch,
		&i.GitCommitHash,
		&i.GitDirectoryPath,
		&i.LastBuiltGitCommitHash,
		&i.CpuLimit,
		&i.MemoryLimit,
		&i.MonthlyBuildTime,
		&i.MonthlyBuildCount,
		&i.MonthlyUptime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsDeleted,
		&i.GithubInstallationID,
	)
	return i, err
}

const getTotalResourceUsageByProject = `-- name: GetTotalResourceUsageByProject :one
SELECT
    COALESCE(SUM(cpu_limit), 0) as total_cpu,
    COALESCE(SUM(memory_limit), 0) as total_memory
FROM CONTAINERS
WHERE project_id = ? AND is_deleted = FALSE
`

type GetTotalResourceUsageByProjectRow struct {
	TotalCpu    interface{} `json:"total_cpu"`
	TotalMemory interface{} `json:"total_memory"`
}

func (q *Queries) GetTotalResourceUsageByProject(ctx context.Context, projectID uint32) (GetTotalResourceUsageByProjectRow, error) {
	row := q.db.QueryRowContext(ctx, getTotalResourceUsageByProject, projectID)
	var i GetTotalResourceUsageByProjectRow
	err := row.Scan(&i.TotalCpu, &i.TotalMemory)
	return i, err
}

const listContainers = `-- name: ListContainers :many
SELECT container_id, project_id, template_id, name, slug, stable_window, template_config, git_repository_url, git_branch, git_commit_hash, git_directory_path, last_built_git_commit_hash, cpu_limit, memory_limit, monthly_build_time, monthly_build_count, monthly_uptime, created_at, updated_at, deleted_at, is_deleted, github_installation_id
FROM CONTAINERS
WHERE is_deleted = FALSE
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListContainersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListContainers(ctx context.Context, arg ListContainersParams) ([]Container, error) {
	rows, err := q.db.QueryContext(ctx, listContainers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Container{}
	for rows.Next() {
		var i Container
		if err := rows.Scan(
			&i.ContainerID,
			&i.ProjectID,
			&i.TemplateID,
			&i.Name,
			&i.Slug,
			&i.StableWindow,
			&i.TemplateConfig,
			&i.GitRepositoryUrl,
			&i.GitBranch,
			&i.GitCommitHash,
			&i.GitDirectoryPath,
			&i.LastBuiltGitCommitHash,
			&i.CpuLimit,
			&i.MemoryLimit,
			&i.MonthlyBuildTime,
			&i.MonthlyBuildCount,
			&i.MonthlyUptime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IsDeleted,
			&i.GithubInstallationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContainersByProjectID = `-- name: ListContainersByProjectID :many
SELECT container_id, project_id, template_id, name, slug, stable_window, template_config, git_repository_url, git_branch, git_commit_hash, git_directory_path, last_built_git_commit_hash, cpu_limit, memory_limit, monthly_build_time, monthly_build_count, monthly_uptime, created_at, updated_at, deleted_at, is_deleted, github_installation_id
FROM CONTAINERS
WHERE project_id = ? AND is_deleted = FALSE
ORDER BY created_at DESC
`

func (q *Queries) ListContainersByProjectID(ctx context.Context, projectID uint32) ([]Container, error) {
	rows, err := q.db.QueryContext(ctx, listContainersByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Container{}
	for rows.Next() {
		var i Container
		if err := rows.Scan(
			&i.ContainerID,
			&i.ProjectID,
			&i.TemplateID,
			&i.Name,
			&i.Slug,
			&i.StableWindow,
			&i.TemplateConfig,
			&i.GitRepositoryUrl,
			&i.GitBranch,
			&i.GitCommitHash,
			&i.GitDirectoryPath,
			&i.LastBuiltGitCommitHash,
			&i.CpuLimit,
			&i.MemoryLimit,
			&i.MonthlyBuildTime,
			&i.MonthlyBuildCount,
			&i.MonthlyUptime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IsDeleted,
			&i.GithubInstallationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContainer = `-- name: UpdateContainer :execresult
UPDATE CONTAINERS SET
    template_id = ?, name = ?, stable_window = ?,
    template_config = ?, github_installation_id = ?,
    git_repository_url = ?, git_branch = ?, git_directory_path = ?, git_commit_hash = ?,
    last_built_git_commit_hash = ?, cpu_limit = ?, memory_limit = ?,
    monthly_build_time = ?, monthly_build_count = ?, monthly_uptime = ?,
    updated_at = ?
WHERE container_id = ? AND is_deleted = FALSE
`

type UpdateContainerParams struct {
	TemplateID             sql.NullInt32   `json:"template_id"`
	Name                   string          `json:"name"`
	StableWindow           sql.NullInt32   `json:"stable_window"`
	TemplateConfig         json.RawMessage `json:"template_config"`
	GithubInstallationID   sql.NullInt64   `json:"github_installation_id"`
	GitRepositoryUrl       sql.NullString  `json:"git_repository_url"`
	GitBranch              sql.NullString  `json:"git_branch"`
	GitDirectoryPath       sql.NullString  `json:"git_directory_path"`
	GitCommitHash          sql.NullString  `json:"git_commit_hash"`
	LastBuiltGitCommitHash sql.NullString  `json:"last_built_git_commit_hash"`
	CpuLimit               sql.NullInt32   `json:"cpu_limit"`
	MemoryLimit            sql.NullInt32   `json:"memory_limit"`
	MonthlyBuildTime       sql.NullInt32   `json:"monthly_build_time"`
	MonthlyBuildCount      sql.NullInt32   `json:"monthly_build_count"`
	MonthlyUptime          sql.NullString  `json:"monthly_uptime"`
	UpdatedAt              sql.NullTime    `json:"updated_at"`
	ContainerID            uint32          `json:"container_id"`
}

func (q *Queries) UpdateContainer(ctx context.Context, arg UpdateContainerParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateContainer,
		arg.TemplateID,
		arg.Name,
		arg.StableWindow,
		arg.TemplateConfig,
		arg.GithubInstallationID,
		arg.GitRepositoryUrl,
		arg.GitBranch,
		arg.GitDirectoryPath,
		arg.GitCommitHash,
		arg.LastBuiltGitCommitHash,
		arg.CpuLimit,
		arg.MemoryLimit,
		arg.MonthlyBuildTime,
		arg.MonthlyBuildCount,
		arg.MonthlyUptime,
		arg.UpdatedAt,
		arg.ContainerID,
	)
}
