// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: env_vars.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countEnvVarsByContainerID = `-- name: CountEnvVarsByContainerID :one
SELECT COUNT(*) as total FROM ENV_VARS WHERE container_id = ?
`

func (q *Queries) CountEnvVarsByContainerID(ctx context.Context, containerID uint32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEnvVarsByContainerID, containerID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createEnvVar = `-- name: CreateEnvVar :execresult

INSERT INTO ENV_VARS (
    container_id, ` + "`" + `key` + "`" + `, value,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?)
`

type CreateEnvVarParams struct {
	ContainerID uint32         `json:"container_id"`
	Key         string         `json:"key"`
	Value       sql.NullString `json:"value"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

// Environment Variables CRUD
func (q *Queries) CreateEnvVar(ctx context.Context, arg CreateEnvVarParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createEnvVar,
		arg.ContainerID,
		arg.Key,
		arg.Value,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const deleteEnvVar = `-- name: DeleteEnvVar :execresult
DELETE FROM ENV_VARS
WHERE container_id = ? AND ` + "`" + `key` + "`" + ` = ?
`

type DeleteEnvVarParams struct {
	ContainerID uint32 `json:"container_id"`
	Key         string `json:"key"`
}

func (q *Queries) DeleteEnvVar(ctx context.Context, arg DeleteEnvVarParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteEnvVar, arg.ContainerID, arg.Key)
}

const deleteEnvVarsByContainerID = `-- name: DeleteEnvVarsByContainerID :execresult
DELETE FROM ENV_VARS
WHERE container_id = ?
`

func (q *Queries) DeleteEnvVarsByContainerID(ctx context.Context, containerID uint32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteEnvVarsByContainerID, containerID)
}

const getEnvVarByKey = `-- name: GetEnvVarByKey :one
SELECT
    env_var_id, container_id, ` + "`" + `key` + "`" + `, value,
    created_at, updated_at
FROM ENV_VARS
WHERE container_id = ? AND ` + "`" + `key` + "`" + ` = ?
`

type GetEnvVarByKeyParams struct {
	ContainerID uint32 `json:"container_id"`
	Key         string `json:"key"`
}

func (q *Queries) GetEnvVarByKey(ctx context.Context, arg GetEnvVarByKeyParams) (EnvVar, error) {
	row := q.db.QueryRowContext(ctx, getEnvVarByKey, arg.ContainerID, arg.Key)
	var i EnvVar
	err := row.Scan(
		&i.EnvVarID,
		&i.ContainerID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnvVarsByContainerID = `-- name: GetEnvVarsByContainerID :many
SELECT
    env_var_id, container_id, ` + "`" + `key` + "`" + `, value,
    created_at, updated_at
FROM ENV_VARS
WHERE container_id = ?
ORDER BY ` + "`" + `key` + "`" + ` ASC
`

func (q *Queries) GetEnvVarsByContainerID(ctx context.Context, containerID uint32) ([]EnvVar, error) {
	rows, err := q.db.QueryContext(ctx, getEnvVarsByContainerID, containerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnvVar{}
	for rows.Next() {
		var i EnvVar
		if err := rows.Scan(
			&i.EnvVarID,
			&i.ContainerID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnvVar = `-- name: UpdateEnvVar :execresult
UPDATE ENV_VARS SET
    value = ?,
    updated_at = ?
WHERE container_id = ? AND ` + "`" + `key` + "`" + ` = ?
`

type UpdateEnvVarParams struct {
	Value       sql.NullString `json:"value"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	ContainerID uint32         `json:"container_id"`
	Key         string         `json:"key"`
}

func (q *Queries) UpdateEnvVar(ctx context.Context, arg UpdateEnvVarParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateEnvVar,
		arg.Value,
		arg.UpdatedAt,
		arg.ContainerID,
		arg.Key,
	)
}
