// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type BuildHistoryStatus string

const (
	BuildHistoryStatusUntracked             BuildHistoryStatus = "untracked"
	BuildHistoryStatusBackendTriggerFailed  BuildHistoryStatus = "backend_trigger_failed"
	BuildHistoryStatusBackendTrackingFailed BuildHistoryStatus = "backend_tracking_failed"
	BuildHistoryStatusBackendTrackingLost   BuildHistoryStatus = "backend_tracking_lost"
	BuildHistoryStatusRunning               BuildHistoryStatus = "running"
	BuildHistoryStatusSuccess               BuildHistoryStatus = "success"
	BuildHistoryStatusFailed                BuildHistoryStatus = "failed"
	BuildHistoryStatusCancelled             BuildHistoryStatus = "cancelled"
	BuildHistoryStatusSkipped               BuildHistoryStatus = "skipped"
)

func (e *BuildHistoryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BuildHistoryStatus(s)
	case string:
		*e = BuildHistoryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BuildHistoryStatus: %T", src)
	}
	return nil
}

type NullBuildHistoryStatus struct {
	BuildHistoryStatus BuildHistoryStatus `json:"build_history_status"`
	Valid              bool               `json:"valid"` // Valid is true if BuildHistoryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBuildHistoryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BuildHistoryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BuildHistoryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBuildHistoryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BuildHistoryStatus), nil
}

type DeploymentsStatus string

const (
	DeploymentsStatusUntracked             DeploymentsStatus = "untracked"
	DeploymentsStatusBackendTriggerFailed  DeploymentsStatus = "backend_trigger_failed"
	DeploymentsStatusBackendTrackingFailed DeploymentsStatus = "backend_tracking_failed"
	DeploymentsStatusBackendTrackingLost   DeploymentsStatus = "backend_tracking_lost"
	DeploymentsStatusRunning               DeploymentsStatus = "running"
	DeploymentsStatusSuccess               DeploymentsStatus = "success"
	DeploymentsStatusFailed                DeploymentsStatus = "failed"
	DeploymentsStatusCancelled             DeploymentsStatus = "cancelled"
)

func (e *DeploymentsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeploymentsStatus(s)
	case string:
		*e = DeploymentsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeploymentsStatus: %T", src)
	}
	return nil
}

type NullDeploymentsStatus struct {
	DeploymentsStatus DeploymentsStatus `json:"deployments_status"`
	Valid             bool              `json:"valid"` // Valid is true if DeploymentsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeploymentsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeploymentsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeploymentsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeploymentsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeploymentsStatus), nil
}

type GithubInstallationsAccountType string

const (
	GithubInstallationsAccountTypeUser         GithubInstallationsAccountType = "User"
	GithubInstallationsAccountTypeOrganization GithubInstallationsAccountType = "Organization"
)

func (e *GithubInstallationsAccountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GithubInstallationsAccountType(s)
	case string:
		*e = GithubInstallationsAccountType(s)
	default:
		return fmt.Errorf("unsupported scan type for GithubInstallationsAccountType: %T", src)
	}
	return nil
}

type NullGithubInstallationsAccountType struct {
	GithubInstallationsAccountType GithubInstallationsAccountType `json:"github_installations_account_type"`
	Valid                          bool                           `json:"valid"` // Valid is true if GithubInstallationsAccountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGithubInstallationsAccountType) Scan(value interface{}) error {
	if value == nil {
		ns.GithubInstallationsAccountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GithubInstallationsAccountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGithubInstallationsAccountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GithubInstallationsAccountType), nil
}

type GithubInstallationsStatus string

const (
	GithubInstallationsStatusActive  GithubInstallationsStatus = "active"
	GithubInstallationsStatusRevoked GithubInstallationsStatus = "revoked"
)

func (e *GithubInstallationsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GithubInstallationsStatus(s)
	case string:
		*e = GithubInstallationsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for GithubInstallationsStatus: %T", src)
	}
	return nil
}

type NullGithubInstallationsStatus struct {
	GithubInstallationsStatus GithubInstallationsStatus `json:"github_installations_status"`
	Valid                     bool                      `json:"valid"` // Valid is true if GithubInstallationsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGithubInstallationsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.GithubInstallationsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GithubInstallationsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGithubInstallationsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GithubInstallationsStatus), nil
}

type NetworksType string

const (
	NetworksTypeTcp  NetworksType = "tcp"
	NetworksTypeUdp  NetworksType = "udp"
	NetworksTypeHttp NetworksType = "http"
)

func (e *NetworksType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NetworksType(s)
	case string:
		*e = NetworksType(s)
	default:
		return fmt.Errorf("unsupported scan type for NetworksType: %T", src)
	}
	return nil
}

type NullNetworksType struct {
	NetworksType NetworksType `json:"networks_type"`
	Valid        bool         `json:"valid"` // Valid is true if NetworksType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNetworksType) Scan(value interface{}) error {
	if value == nil {
		ns.NetworksType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NetworksType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNetworksType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NetworksType), nil
}

type ProjectUserRole string

const (
	ProjectUserRoleOwner  ProjectUserRole = "owner"
	ProjectUserRoleMember ProjectUserRole = "member"
	ProjectUserRoleGuest  ProjectUserRole = "guest"
)

func (e *ProjectUserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProjectUserRole(s)
	case string:
		*e = ProjectUserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for ProjectUserRole: %T", src)
	}
	return nil
}

type NullProjectUserRole struct {
	ProjectUserRole ProjectUserRole `json:"project_user_role"`
	Valid           bool            `json:"valid"` // Valid is true if ProjectUserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProjectUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.ProjectUserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProjectUserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProjectUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProjectUserRole), nil
}

type ProjectsProjectOperationStatus string

const (
	ProjectsProjectOperationStatusNothing   ProjectsProjectOperationStatus = "nothing"
	ProjectsProjectOperationStatusBuilding  ProjectsProjectOperationStatus = "building"
	ProjectsProjectOperationStatusDeploying ProjectsProjectOperationStatus = "deploying"
)

func (e *ProjectsProjectOperationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProjectsProjectOperationStatus(s)
	case string:
		*e = ProjectsProjectOperationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProjectsProjectOperationStatus: %T", src)
	}
	return nil
}

type NullProjectsProjectOperationStatus struct {
	ProjectsProjectOperationStatus ProjectsProjectOperationStatus `json:"projects_project_operation_status"`
	Valid                          bool                           `json:"valid"` // Valid is true if ProjectsProjectOperationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProjectsProjectOperationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProjectsProjectOperationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProjectsProjectOperationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProjectsProjectOperationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProjectsProjectOperationStatus), nil
}

type ProjectsStatus string

const (
	ProjectsStatusActive    ProjectsStatus = "active"
	ProjectsStatusInactive  ProjectsStatus = "inactive"
	ProjectsStatusSuspended ProjectsStatus = "suspended"
	ProjectsStatusPending   ProjectsStatus = "pending"
)

func (e *ProjectsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProjectsStatus(s)
	case string:
		*e = ProjectsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProjectsStatus: %T", src)
	}
	return nil
}

type NullProjectsStatus struct {
	ProjectsStatus ProjectsStatus `json:"projects_status"`
	Valid          bool           `json:"valid"` // Valid is true if ProjectsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProjectsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProjectsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProjectsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProjectsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProjectsStatus), nil
}

type SystemSettingsValueType string

const (
	SystemSettingsValueTypeString  SystemSettingsValueType = "string"
	SystemSettingsValueTypeInt     SystemSettingsValueType = "int"
	SystemSettingsValueTypeFloat   SystemSettingsValueType = "float"
	SystemSettingsValueTypeBoolean SystemSettingsValueType = "boolean"
	SystemSettingsValueTypeJson    SystemSettingsValueType = "json"
)

func (e *SystemSettingsValueType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SystemSettingsValueType(s)
	case string:
		*e = SystemSettingsValueType(s)
	default:
		return fmt.Errorf("unsupported scan type for SystemSettingsValueType: %T", src)
	}
	return nil
}

type NullSystemSettingsValueType struct {
	SystemSettingsValueType SystemSettingsValueType `json:"system_settings_value_type"`
	Valid                   bool                    `json:"valid"` // Valid is true if SystemSettingsValueType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSystemSettingsValueType) Scan(value interface{}) error {
	if value == nil {
		ns.SystemSettingsValueType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SystemSettingsValueType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSystemSettingsValueType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SystemSettingsValueType), nil
}

type TemplatesStatus string

const (
	TemplatesStatusActive     TemplatesStatus = "active"
	TemplatesStatusInactive   TemplatesStatus = "inactive"
	TemplatesStatusDeprecated TemplatesStatus = "deprecated"
)

func (e *TemplatesStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TemplatesStatus(s)
	case string:
		*e = TemplatesStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TemplatesStatus: %T", src)
	}
	return nil
}

type NullTemplatesStatus struct {
	TemplatesStatus TemplatesStatus `json:"templates_status"`
	Valid           bool            `json:"valid"` // Valid is true if TemplatesStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTemplatesStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TemplatesStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TemplatesStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTemplatesStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TemplatesStatus), nil
}

type UsersStatus string

const (
	UsersStatusActive    UsersStatus = "active"
	UsersStatusInactive  UsersStatus = "inactive"
	UsersStatusSuspended UsersStatus = "suspended"
	UsersStatusPending   UsersStatus = "pending"
)

func (e *UsersStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersStatus(s)
	case string:
		*e = UsersStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersStatus: %T", src)
	}
	return nil
}

type NullUsersStatus struct {
	UsersStatus UsersStatus `json:"users_status"`
	Valid       bool        `json:"valid"` // Valid is true if UsersStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UsersStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersStatus), nil
}

type VerificationTokensTokenType string

const (
	VerificationTokensTokenTypeEmailVerification VerificationTokensTokenType = "email_verification"
	VerificationTokensTokenTypePasswordReset     VerificationTokensTokenType = "password_reset"
)

func (e *VerificationTokensTokenType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VerificationTokensTokenType(s)
	case string:
		*e = VerificationTokensTokenType(s)
	default:
		return fmt.Errorf("unsupported scan type for VerificationTokensTokenType: %T", src)
	}
	return nil
}

type NullVerificationTokensTokenType struct {
	VerificationTokensTokenType VerificationTokensTokenType `json:"verification_tokens_token_type"`
	Valid                       bool                        `json:"valid"` // Valid is true if VerificationTokensTokenType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVerificationTokensTokenType) Scan(value interface{}) error {
	if value == nil {
		ns.VerificationTokensTokenType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VerificationTokensTokenType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVerificationTokensTokenType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VerificationTokensTokenType), nil
}

type BuildHistory struct {
	BuildHistoryID uint32             `json:"build_history_id"`
	ContainerID    uint32             `json:"container_id"`
	Status         BuildHistoryStatus `json:"status"`
	Summary        sql.NullString     `json:"summary"`
	// Tekton event ID from API response
	TektonEventID sql.NullString `json:"tekton_event_id"`
	// Tekton PipelineRun name
	TektonPipelineRunName sql.NullString `json:"tekton_pipeline_run_name"`
	// Latest commit hash from Tekton build result
	GitCommitHash sql.NullString `json:"git_commit_hash"`
	CreatedAt     time.Time      `json:"created_at"`
	StartedAt     sql.NullTime   `json:"started_at"`
	FinishedAt    sql.NullTime   `json:"finished_at"`
}

type BuildVar struct {
	BuildVarID  uint32         `json:"build_var_id"`
	ContainerID uint32         `json:"container_id"`
	Key         string         `json:"key"`
	Value       sql.NullString `json:"value"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Container struct {
	ContainerID            uint32          `json:"container_id"`
	ProjectID              uint32          `json:"project_id"`
	TemplateID             sql.NullInt32   `json:"template_id"`
	Name                   string          `json:"name"`
	Slug                   string          `json:"slug"`
	StableWindow           sql.NullInt32   `json:"stable_window"`
	TemplateConfig         json.RawMessage `json:"template_config"`
	GithubInstallationID   sql.NullInt64   `json:"github_installation_id"`
	GitRepositoryUrl       sql.NullString  `json:"git_repository_url"`
	GitBranch              sql.NullString  `json:"git_branch"`
	GitCommitHash          sql.NullString  `json:"git_commit_hash"`
	GitDirectoryPath       sql.NullString  `json:"git_directory_path"`
	LastBuiltGitCommitHash sql.NullString  `json:"last_built_git_commit_hash"`
	// Indicates whether build is required (set to true when build parameters change)
	NeedsBuild        bool           `json:"needs_build"`
	CpuLimit          sql.NullInt32  `json:"cpu_limit"`
	MemoryLimit       sql.NullInt32  `json:"memory_limit"`
	MonthlyBuildTime  sql.NullInt32  `json:"monthly_build_time"`
	MonthlyBuildCount sql.NullInt32  `json:"monthly_build_count"`
	MonthlyUptime     sql.NullString `json:"monthly_uptime"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
	DeletedAt         sql.NullTime   `json:"deleted_at"`
	IsDeleted         bool           `json:"is_deleted"`
}

type Deployment struct {
	DeploymentID uint32            `json:"deployment_id"`
	ProjectID    uint32            `json:"project_id"`
	Status       DeploymentsStatus `json:"status"`
	Summary      sql.NullString    `json:"summary"`
	// Tekton event ID from API response
	TektonEventID sql.NullString `json:"tekton_event_id"`
	// Tekton PipelineRun name
	TektonPipelineRunName sql.NullString `json:"tekton_pipeline_run_name"`
	CreatedAt             time.Time      `json:"created_at"`
	StartedAt             sql.NullTime   `json:"started_at"`
	FinishedAt            sql.NullTime   `json:"finished_at"`
}

type EnvVar struct {
	EnvVarID    uint32         `json:"env_var_id"`
	ContainerID uint32         `json:"container_id"`
	Key         string         `json:"key"`
	Value       sql.NullString `json:"value"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type GithubInstallation struct {
	InstallationID uint64                         `json:"installation_id"`
	UserID         uint32                         `json:"user_id"`
	AccountLogin   string                         `json:"account_login"`
	AccountType    GithubInstallationsAccountType `json:"account_type"`
	Status         GithubInstallationsStatus      `json:"status"`
	CachedToken    sql.NullString                 `json:"cached_token"`
	TokenExpiresAt sql.NullTime                   `json:"token_expires_at"`
	CreatedAt      time.Time                      `json:"created_at"`
	UpdatedAt      sql.NullTime                   `json:"updated_at"`
	DeletedAt      sql.NullTime                   `json:"deleted_at"`
	IsDeleted      bool                           `json:"is_deleted"`
}

type Mount struct {
	ContainerID uint32       `json:"container_id"`
	VolumeID    uint32       `json:"volume_id"`
	MountPath   string       `json:"mount_path"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

type Network struct {
	NetworkID    uint32         `json:"network_id"`
	ContainerID  uint32         `json:"container_id"`
	ExternalIp   sql.NullString `json:"external_ip"`
	Fqdn         sql.NullString `json:"fqdn"`
	ExternalPort sql.NullInt32  `json:"external_port"`
	InternalPort sql.NullInt32  `json:"internal_port"`
	Type         NetworksType   `json:"type"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type OauthState struct {
	State          string        `json:"state"`
	UserID         uint32        `json:"user_id"`
	InstallationID sql.NullInt64 `json:"installation_id"`
	ExpiresAt      time.Time     `json:"expires_at"`
	CreatedAt      time.Time     `json:"created_at"`
	ConsumedAt     sql.NullTime  `json:"consumed_at"`
}

type Project struct {
	ProjectID uint32         `json:"project_id"`
	Name      string         `json:"name"`
	Slug      string         `json:"slug"`
	Fqdn      sql.NullString `json:"fqdn"`
	Status    ProjectsStatus `json:"status"`
	// Current operation status of the project
	ProjectOperationStatus ProjectsProjectOperationStatus `json:"project_operation_status"`
	// ID of the deployment that currently owns the deploying status
	ActiveDeploymentID sql.NullInt32  `json:"active_deployment_id"`
	Plan               sql.NullString `json:"plan"`
	CpuLimit           sql.NullInt32  `json:"cpu_limit"`
	MemoryLimit        sql.NullInt32  `json:"memory_limit"`
	DiskLimit          sql.NullInt32  `json:"disk_limit"`
	TrafficLimit       sql.NullInt64  `json:"traffic_limit"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          sql.NullTime   `json:"updated_at"`
	DeletedAt          sql.NullTime   `json:"deleted_at"`
	IsDeleted          bool           `json:"is_deleted"`
}

type ProjectUser struct {
	ProjectUserID uint32          `json:"project_user_id"`
	ProjectID     uint32          `json:"project_id"`
	UserID        uint32          `json:"user_id"`
	Role          ProjectUserRole `json:"role"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     sql.NullTime    `json:"updated_at"`
	DeletedAt     sql.NullTime    `json:"deleted_at"`
	IsDeleted     bool            `json:"is_deleted"`
}

type Secret struct {
	SecretID    uint32         `json:"secret_id"`
	ContainerID uint32         `json:"container_id"`
	Key         string         `json:"key"`
	Value       sql.NullString `json:"value"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type SystemSetting struct {
	SettingKey   string                  `json:"setting_key"`
	SettingValue string                  `json:"setting_value"`
	ValueType    SystemSettingsValueType `json:"value_type"`
	Category     string                  `json:"category"`
	Description  sql.NullString          `json:"description"`
	IsEditable   sql.NullBool            `json:"is_editable"`
	UpdatedBy    sql.NullInt32           `json:"updated_by"`
	CreatedAt    sql.NullTime            `json:"created_at"`
	UpdatedAt    sql.NullTime            `json:"updated_at"`
}

type Template struct {
	TemplateID     uint32          `json:"template_id"`
	Name           string          `json:"name"`
	TemplateBody   sql.NullString  `json:"template_body"`
	TemplateConfig json.RawMessage `json:"template_config"`
	Status         TemplatesStatus `json:"status"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      sql.NullTime    `json:"updated_at"`
}

type User struct {
	UserID            uint32         `json:"user_id"`
	Username          string         `json:"username"`
	PasswordHash      string         `json:"password_hash"`
	PasswordUpdatedAt sql.NullTime   `json:"password_updated_at"`
	Name              sql.NullString `json:"name"`
	Email             string         `json:"email"`
	Phone             sql.NullString `json:"phone"`
	Status            UsersStatus    `json:"status"`
	Organization      sql.NullString `json:"organization"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
	DeletedAt         sql.NullTime   `json:"deleted_at"`
	IsDeleted         bool           `json:"is_deleted"`
}

type VerificationToken struct {
	TokenID   uint32                      `json:"token_id"`
	UserID    uint32                      `json:"user_id"`
	Token     string                      `json:"token"`
	TokenType VerificationTokensTokenType `json:"token_type"`
	ExpiresAt time.Time                   `json:"expires_at"`
	UsedAt    sql.NullTime                `json:"used_at"`
	CreatedAt time.Time                   `json:"created_at"`
}

type Volume struct {
	VolumeID  uint32         `json:"volume_id"`
	ProjectID uint32         `json:"project_id"`
	Name      string         `json:"name"`
	Slug      sql.NullString `json:"slug"`
	Capacity  uint32         `json:"capacity"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}
