// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mounts.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countMountsByContainerID = `-- name: CountMountsByContainerID :one
SELECT COUNT(*) as total FROM MOUNTS WHERE container_id = ?
`

func (q *Queries) CountMountsByContainerID(ctx context.Context, containerID uint32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMountsByContainerID, containerID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createMount = `-- name: CreateMount :execresult

INSERT INTO MOUNTS (
    container_id, volume_id, mount_path,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?)
`

type CreateMountParams struct {
	ContainerID uint32       `json:"container_id"`
	VolumeID    uint32       `json:"volume_id"`
	MountPath   string       `json:"mount_path"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

// Volume Mounts CRUD
func (q *Queries) CreateMount(ctx context.Context, arg CreateMountParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMount,
		arg.ContainerID,
		arg.VolumeID,
		arg.MountPath,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const deleteMount = `-- name: DeleteMount :execresult
DELETE FROM MOUNTS
WHERE container_id = ? AND volume_id = ?
`

type DeleteMountParams struct {
	ContainerID uint32 `json:"container_id"`
	VolumeID    uint32 `json:"volume_id"`
}

func (q *Queries) DeleteMount(ctx context.Context, arg DeleteMountParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteMount, arg.ContainerID, arg.VolumeID)
}

const deleteMountsByContainerID = `-- name: DeleteMountsByContainerID :execresult
DELETE FROM MOUNTS
WHERE container_id = ?
`

func (q *Queries) DeleteMountsByContainerID(ctx context.Context, containerID uint32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteMountsByContainerID, containerID)
}

const existsMountByVolume = `-- name: ExistsMountByVolume :one
SELECT EXISTS(
    SELECT 1 FROM MOUNTS
    WHERE container_id = ? AND volume_id = ?
) as ` + "`" + `exists` + "`" + `
`

type ExistsMountByVolumeParams struct {
	ContainerID uint32 `json:"container_id"`
	VolumeID    uint32 `json:"volume_id"`
}

func (q *Queries) ExistsMountByVolume(ctx context.Context, arg ExistsMountByVolumeParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsMountByVolume, arg.ContainerID, arg.VolumeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getMountByVolume = `-- name: GetMountByVolume :one
SELECT
    container_id, volume_id, mount_path,
    created_at, updated_at
FROM MOUNTS
WHERE container_id = ? AND volume_id = ?
`

type GetMountByVolumeParams struct {
	ContainerID uint32 `json:"container_id"`
	VolumeID    uint32 `json:"volume_id"`
}

func (q *Queries) GetMountByVolume(ctx context.Context, arg GetMountByVolumeParams) (Mount, error) {
	row := q.db.QueryRowContext(ctx, getMountByVolume, arg.ContainerID, arg.VolumeID)
	var i Mount
	err := row.Scan(
		&i.ContainerID,
		&i.VolumeID,
		&i.MountPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMountsByContainerID = `-- name: GetMountsByContainerID :many
SELECT
    container_id, volume_id, mount_path,
    created_at, updated_at
FROM MOUNTS
WHERE container_id = ?
ORDER BY mount_path ASC
`

func (q *Queries) GetMountsByContainerID(ctx context.Context, containerID uint32) ([]Mount, error) {
	rows, err := q.db.QueryContext(ctx, getMountsByContainerID, containerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Mount{}
	for rows.Next() {
		var i Mount
		if err := rows.Scan(
			&i.ContainerID,
			&i.VolumeID,
			&i.MountPath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
