// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: networks.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countNetworksByContainerID = `-- name: CountNetworksByContainerID :one
SELECT COUNT(*) as total FROM NETWORKS WHERE container_id = ?
`

func (q *Queries) CountNetworksByContainerID(ctx context.Context, containerID uint32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNetworksByContainerID, containerID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createNetwork = `-- name: CreateNetwork :execresult

INSERT INTO NETWORKS (
    container_id, internal_port, external_port, external_ip, fqdn, type,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateNetworkParams struct {
	ContainerID  uint32         `json:"container_id"`
	InternalPort sql.NullInt16  `json:"internal_port"`
	ExternalPort sql.NullInt16  `json:"external_port"`
	ExternalIp   sql.NullString `json:"external_ip"`
	Fqdn         sql.NullString `json:"fqdn"`
	Type         NetworksType   `json:"type"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

// Networks CRUD
func (q *Queries) CreateNetwork(ctx context.Context, arg CreateNetworkParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createNetwork,
		arg.ContainerID,
		arg.InternalPort,
		arg.ExternalPort,
		arg.ExternalIp,
		arg.Fqdn,
		arg.Type,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const deleteNetwork = `-- name: DeleteNetwork :execresult
DELETE FROM NETWORKS
WHERE network_id = ?
`

func (q *Queries) DeleteNetwork(ctx context.Context, networkID uint32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteNetwork, networkID)
}

const deleteNetworksByContainerID = `-- name: DeleteNetworksByContainerID :execresult
DELETE FROM NETWORKS
WHERE container_id = ?
`

func (q *Queries) DeleteNetworksByContainerID(ctx context.Context, containerID uint32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteNetworksByContainerID, containerID)
}

const getNetworkByID = `-- name: GetNetworkByID :one
SELECT network_id, container_id, external_ip, fqdn, external_port, internal_port, type, created_at, updated_at
FROM NETWORKS
WHERE network_id = ?
`

func (q *Queries) GetNetworkByID(ctx context.Context, networkID uint32) (Network, error) {
	row := q.db.QueryRowContext(ctx, getNetworkByID, networkID)
	var i Network
	err := row.Scan(
		&i.NetworkID,
		&i.ContainerID,
		&i.ExternalIp,
		&i.Fqdn,
		&i.ExternalPort,
		&i.InternalPort,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNetworksByContainerID = `-- name: GetNetworksByContainerID :many
SELECT network_id, container_id, external_ip, fqdn, external_port, internal_port, type, created_at, updated_at
FROM NETWORKS
WHERE container_id = ?
ORDER BY internal_port ASC
`

func (q *Queries) GetNetworksByContainerID(ctx context.Context, containerID uint32) ([]Network, error) {
	rows, err := q.db.QueryContext(ctx, getNetworksByContainerID, containerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Network{}
	for rows.Next() {
		var i Network
		if err := rows.Scan(
			&i.NetworkID,
			&i.ContainerID,
			&i.ExternalIp,
			&i.Fqdn,
			&i.ExternalPort,
			&i.InternalPort,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNetwork = `-- name: UpdateNetwork :execresult
UPDATE NETWORKS SET
    external_port = ?,
    external_ip = ?,
    fqdn = ?,
    updated_at = ?
WHERE network_id = ?
`

type UpdateNetworkParams struct {
	ExternalPort sql.NullInt16  `json:"external_port"`
	ExternalIp   sql.NullString `json:"external_ip"`
	Fqdn         sql.NullString `json:"fqdn"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
	NetworkID    uint32         `json:"network_id"`
}

func (q *Queries) UpdateNetwork(ctx context.Context, arg UpdateNetworkParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateNetwork,
		arg.ExternalPort,
		arg.ExternalIp,
		arg.Fqdn,
		arg.UpdatedAt,
		arg.NetworkID,
	)
}
