// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: networks.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const checkFQDNExists = `-- name: CheckFQDNExists :one
SELECT COUNT(*) > 0 as fqdn_exists
FROM NETWORKS n
INNER JOIN CONTAINERS c ON n.container_id = c.container_id
WHERE n.fqdn = ?
  AND n.is_deleted = 0
  AND c.is_deleted = 0
FOR UPDATE
`

// Check if FQDN is used anywhere in the system
// Simple availability check across all projects
func (q *Queries) CheckFQDNExists(ctx context.Context, fqdn sql.NullString) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkFQDNExists, fqdn)
	var fqdn_exists bool
	err := row.Scan(&fqdn_exists)
	return fqdn_exists, err
}

const checkFQDNExistsForProject = `-- name: CheckFQDNExistsForProject :one
SELECT COUNT(*) > 0 as fqdn_exists
FROM NETWORKS n
INNER JOIN CONTAINERS c ON n.container_id = c.container_id
WHERE n.fqdn = ?
  AND n.is_deleted = 0
  AND (
    c.project_id = ?
    OR (c.project_id != ? AND c.is_deleted = 0)
  )
FOR UPDATE
`

type CheckFQDNExistsForProjectParams struct {
	Fqdn        sql.NullString `json:"fqdn"`
	ProjectID   uint32         `json:"project_id"`
	ProjectID_2 uint32         `json:"project_id_2"`
}

// Check FQDN with proper business rules for AddNetwork/CreateContainer
// Returns true if FQDN exists in:
// 1. Same project (any active network, regardless of container state)
// 2. Other projects (only if container is active - maintains ownership)
// Allows reuse when:
// - Same project soft-deleted network (deployment time same, no conflict)
// - Other project soft-deleted container (ownership released)
func (q *Queries) CheckFQDNExistsForProject(ctx context.Context, arg CheckFQDNExistsForProjectParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkFQDNExistsForProject, arg.Fqdn, arg.ProjectID, arg.ProjectID_2)
	var fqdn_exists bool
	err := row.Scan(&fqdn_exists)
	return fqdn_exists, err
}

const checkFQDNExistsForProjectExcludingSelf = `-- name: CheckFQDNExistsForProjectExcludingSelf :one
SELECT COUNT(*) > 0 as fqdn_exists
FROM NETWORKS n
INNER JOIN CONTAINERS c ON n.container_id = c.container_id
WHERE n.fqdn = ?
  AND n.network_id != ?
  AND n.is_deleted = 0
  AND (
    c.project_id = ?
    OR (c.project_id != ? AND c.is_deleted = 0)
  )
FOR UPDATE
`

type CheckFQDNExistsForProjectExcludingSelfParams struct {
	Fqdn        sql.NullString `json:"fqdn"`
	NetworkID   uint32         `json:"network_id"`
	ProjectID   uint32         `json:"project_id"`
	ProjectID_2 uint32         `json:"project_id_2"`
}

// Same as CheckFQDNExistsForProject but excludes self (for UpdateNetwork)
func (q *Queries) CheckFQDNExistsForProjectExcludingSelf(ctx context.Context, arg CheckFQDNExistsForProjectExcludingSelfParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkFQDNExistsForProjectExcludingSelf,
		arg.Fqdn,
		arg.NetworkID,
		arg.ProjectID,
		arg.ProjectID_2,
	)
	var fqdn_exists bool
	err := row.Scan(&fqdn_exists)
	return fqdn_exists, err
}

const checkFQDNExistsInOtherProject = `-- name: CheckFQDNExistsInOtherProject :one
SELECT COUNT(*) > 0 as fqdn_exists
FROM NETWORKS n
INNER JOIN CONTAINERS c ON n.container_id = c.container_id
WHERE n.fqdn = ?
  AND c.project_id != ?
  AND c.is_deleted = 0
FOR UPDATE
`

type CheckFQDNExistsInOtherProjectParams struct {
	Fqdn      sql.NullString `json:"fqdn"`
	ProjectID uint32         `json:"project_id"`
}

// Check if FQDN is used by another project (for AddNetwork)
// FQDN ownership is project-scoped: once a project uses a FQDN, it's reserved for that project
// Checks both active and deleted networks to preserve FQDN ownership
func (q *Queries) CheckFQDNExistsInOtherProject(ctx context.Context, arg CheckFQDNExistsInOtherProjectParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkFQDNExistsInOtherProject, arg.Fqdn, arg.ProjectID)
	var fqdn_exists bool
	err := row.Scan(&fqdn_exists)
	return fqdn_exists, err
}

const checkFQDNExistsInOtherProjectExcludingSelf = `-- name: CheckFQDNExistsInOtherProjectExcludingSelf :one
SELECT COUNT(*) > 0 as fqdn_exists
FROM NETWORKS n
INNER JOIN CONTAINERS c ON n.container_id = c.container_id
WHERE n.fqdn = ?
  AND n.network_id != ?
  AND c.project_id != ?
  AND c.is_deleted = 0
FOR UPDATE
`

type CheckFQDNExistsInOtherProjectExcludingSelfParams struct {
	Fqdn      sql.NullString `json:"fqdn"`
	NetworkID uint32         `json:"network_id"`
	ProjectID uint32         `json:"project_id"`
}

// Check if FQDN is used by another project, excluding self (for UpdateNetwork)
// Allows updating a network's FQDN to the same value or reusing FQDN within same project
// Checks both active and deleted networks to preserve FQDN ownership
func (q *Queries) CheckFQDNExistsInOtherProjectExcludingSelf(ctx context.Context, arg CheckFQDNExistsInOtherProjectExcludingSelfParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkFQDNExistsInOtherProjectExcludingSelf, arg.Fqdn, arg.NetworkID, arg.ProjectID)
	var fqdn_exists bool
	err := row.Scan(&fqdn_exists)
	return fqdn_exists, err
}

const checkInternalPortExistsInProject = `-- name: CheckInternalPortExistsInProject :one
SELECT COUNT(*) > 0 as port_exists
FROM NETWORKS n
INNER JOIN CONTAINERS c ON n.container_id = c.container_id
WHERE c.project_id = ?
  AND n.internal_port = ?
  AND n.is_deleted = 0
  AND c.is_deleted = 0
FOR UPDATE
`

type CheckInternalPortExistsInProjectParams struct {
	ProjectID    uint32        `json:"project_id"`
	InternalPort sql.NullInt32 `json:"internal_port"`
}

func (q *Queries) CheckInternalPortExistsInProject(ctx context.Context, arg CheckInternalPortExistsInProjectParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkInternalPortExistsInProject, arg.ProjectID, arg.InternalPort)
	var port_exists bool
	err := row.Scan(&port_exists)
	return port_exists, err
}

const checkInternalPortExistsInProjectExcludingSelf = `-- name: CheckInternalPortExistsInProjectExcludingSelf :one
SELECT COUNT(*) > 0 as port_exists
FROM NETWORKS n
INNER JOIN CONTAINERS c ON n.container_id = c.container_id
WHERE c.project_id = ?
  AND n.internal_port = ?
  AND n.network_id != ?
  AND n.is_deleted = 0
  AND c.is_deleted = 0
FOR UPDATE
`

type CheckInternalPortExistsInProjectExcludingSelfParams struct {
	ProjectID    uint32        `json:"project_id"`
	InternalPort sql.NullInt32 `json:"internal_port"`
	NetworkID    uint32        `json:"network_id"`
}

// Check if internal port exists in project, excluding self (for UpdateNetwork)
// Internal ports must be unique within a project (containers share pod network interface)
func (q *Queries) CheckInternalPortExistsInProjectExcludingSelf(ctx context.Context, arg CheckInternalPortExistsInProjectExcludingSelfParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkInternalPortExistsInProjectExcludingSelf, arg.ProjectID, arg.InternalPort, arg.NetworkID)
	var port_exists bool
	err := row.Scan(&port_exists)
	return port_exists, err
}

const countNetworksByContainerID = `-- name: CountNetworksByContainerID :one
SELECT COUNT(*) as total FROM NETWORKS WHERE container_id = ?
`

func (q *Queries) CountNetworksByContainerID(ctx context.Context, containerID uint32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNetworksByContainerID, containerID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createNetwork = `-- name: CreateNetwork :execresult

INSERT INTO NETWORKS (
    container_id, internal_port, external_port, external_ip, fqdn, type,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateNetworkParams struct {
	ContainerID  uint32         `json:"container_id"`
	InternalPort sql.NullInt32  `json:"internal_port"`
	ExternalPort sql.NullInt32  `json:"external_port"`
	ExternalIp   sql.NullString `json:"external_ip"`
	Fqdn         sql.NullString `json:"fqdn"`
	Type         NetworksType   `json:"type"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

// Networks CRUD
func (q *Queries) CreateNetwork(ctx context.Context, arg CreateNetworkParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createNetwork,
		arg.ContainerID,
		arg.InternalPort,
		arg.ExternalPort,
		arg.ExternalIp,
		arg.Fqdn,
		arg.Type,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const deleteNetwork = `-- name: DeleteNetwork :execresult
UPDATE NETWORKS SET
    is_deleted = TRUE,
    deleted_at = ?
WHERE network_id = ?
`

type DeleteNetworkParams struct {
	DeletedAt sql.NullTime `json:"deleted_at"`
	NetworkID uint32       `json:"network_id"`
}

func (q *Queries) DeleteNetwork(ctx context.Context, arg DeleteNetworkParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteNetwork, arg.DeletedAt, arg.NetworkID)
}

const deleteNetworksByContainerID = `-- name: DeleteNetworksByContainerID :execresult
DELETE FROM NETWORKS
WHERE container_id = ?
`

func (q *Queries) DeleteNetworksByContainerID(ctx context.Context, containerID uint32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteNetworksByContainerID, containerID)
}

const getNetworkByID = `-- name: GetNetworkByID :one
SELECT network_id, container_id, external_ip, fqdn, external_port, internal_port, type, created_at, updated_at, is_deleted, deleted_at, tekton_event_id, expires_at
FROM NETWORKS
WHERE network_id = ?
`

func (q *Queries) GetNetworkByID(ctx context.Context, networkID uint32) (Network, error) {
	row := q.db.QueryRowContext(ctx, getNetworkByID, networkID)
	var i Network
	err := row.Scan(
		&i.NetworkID,
		&i.ContainerID,
		&i.ExternalIp,
		&i.Fqdn,
		&i.ExternalPort,
		&i.InternalPort,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.TektonEventID,
		&i.ExpiresAt,
	)
	return i, err
}

const getNetworksByContainerID = `-- name: GetNetworksByContainerID :many
SELECT network_id, container_id, external_ip, fqdn, external_port, internal_port, type, created_at, updated_at, is_deleted, deleted_at, tekton_event_id, expires_at
FROM NETWORKS
WHERE container_id = ?
  AND is_deleted = 0
ORDER BY internal_port ASC
`

func (q *Queries) GetNetworksByContainerID(ctx context.Context, containerID uint32) ([]Network, error) {
	rows, err := q.db.QueryContext(ctx, getNetworksByContainerID, containerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Network{}
	for rows.Next() {
		var i Network
		if err := rows.Scan(
			&i.NetworkID,
			&i.ContainerID,
			&i.ExternalIp,
			&i.Fqdn,
			&i.ExternalPort,
			&i.InternalPort,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.TektonEventID,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteNetworkByID = `-- name: SoftDeleteNetworkByID :execresult
UPDATE NETWORKS SET
    is_deleted = TRUE,
    deleted_at = ?,
    fqdn = NULL
WHERE network_id = ?
  AND is_deleted = 0
`

type SoftDeleteNetworkByIDParams struct {
	DeletedAt sql.NullTime `json:"deleted_at"`
	NetworkID uint32       `json:"network_id"`
}

// Soft delete a specific network by ID
// Clear FQDN to allow reuse while preserving ownership tracking
func (q *Queries) SoftDeleteNetworkByID(ctx context.Context, arg SoftDeleteNetworkByIDParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, softDeleteNetworkByID, arg.DeletedAt, arg.NetworkID)
}

const softDeleteNetworksByContainerID = `-- name: SoftDeleteNetworksByContainerID :execresult
UPDATE NETWORKS SET
    is_deleted = TRUE,
    deleted_at = ?,
    fqdn = NULL
WHERE container_id = ?
  AND is_deleted = 0
`

type SoftDeleteNetworksByContainerIDParams struct {
	DeletedAt   sql.NullTime `json:"deleted_at"`
	ContainerID uint32       `json:"container_id"`
}

// Soft delete all networks when a container is deleted
// Clear FQDN to allow reuse while preserving ownership tracking
func (q *Queries) SoftDeleteNetworksByContainerID(ctx context.Context, arg SoftDeleteNetworksByContainerIDParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, softDeleteNetworksByContainerID, arg.DeletedAt, arg.ContainerID)
}

const updateNetwork = `-- name: UpdateNetwork :execresult
UPDATE NETWORKS SET
    internal_port = ?,
    type = ?,
    external_port = ?,
    external_ip = ?,
    fqdn = ?,
    updated_at = ?
WHERE network_id = ?
`

type UpdateNetworkParams struct {
	InternalPort sql.NullInt32  `json:"internal_port"`
	Type         NetworksType   `json:"type"`
	ExternalPort sql.NullInt32  `json:"external_port"`
	ExternalIp   sql.NullString `json:"external_ip"`
	Fqdn         sql.NullString `json:"fqdn"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
	NetworkID    uint32         `json:"network_id"`
}

func (q *Queries) UpdateNetwork(ctx context.Context, arg UpdateNetworkParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateNetwork,
		arg.InternalPort,
		arg.Type,
		arg.ExternalPort,
		arg.ExternalIp,
		arg.Fqdn,
		arg.UpdatedAt,
		arg.NetworkID,
	)
}

const updateNetworkNodePortResult = `-- name: UpdateNetworkNodePortResult :exec
UPDATE NETWORKS SET
    external_ip = ?,
    external_port = ?,
    expires_at = ?,
    updated_at = NOW()
WHERE network_id = ?
`

type UpdateNetworkNodePortResultParams struct {
	ExternalIp   sql.NullString `json:"external_ip"`
	ExternalPort sql.NullInt32  `json:"external_port"`
	ExpiresAt    sql.NullTime   `json:"expires_at"`
	NetworkID    uint32         `json:"network_id"`
}

// Update NodePort result fields when PipelineRun completes
func (q *Queries) UpdateNetworkNodePortResult(ctx context.Context, arg UpdateNetworkNodePortResultParams) error {
	_, err := q.db.ExecContext(ctx, updateNetworkNodePortResult,
		arg.ExternalIp,
		arg.ExternalPort,
		arg.ExpiresAt,
		arg.NetworkID,
	)
	return err
}

const updateNetworkTektonEventID = `-- name: UpdateNetworkTektonEventID :exec
UPDATE NETWORKS SET
    tekton_event_id = ?,
    external_ip = NULL,
    external_port = NULL,
    expires_at = NULL,
    updated_at = NOW()
WHERE network_id = ?
`

type UpdateNetworkTektonEventIDParams struct {
	TektonEventID sql.NullString `json:"tekton_event_id"`
	NetworkID     uint32         `json:"network_id"`
}

// Update Tekton PipelineRun name and clear NodePort fields when starting new creation
func (q *Queries) UpdateNetworkTektonEventID(ctx context.Context, arg UpdateNetworkTektonEventIDParams) error {
	_, err := q.db.ExecContext(ctx, updateNetworkTektonEventID, arg.TektonEventID, arg.NetworkID)
	return err
}
