// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	// Check if FQDN is used by another project (for AddNetwork)
	// FQDN ownership is project-scoped: once a project uses a FQDN, it's reserved for that project
	// Checks both active and deleted networks to preserve FQDN ownership
	CheckFQDNExistsInOtherProject(ctx context.Context, arg CheckFQDNExistsInOtherProjectParams) (bool, error)
	// Check if FQDN is used by another project, excluding self (for UpdateNetwork)
	// Allows updating a network's FQDN to the same value or reusing FQDN within same project
	// Checks both active and deleted networks to preserve FQDN ownership
	CheckFQDNExistsInOtherProjectExcludingSelf(ctx context.Context, arg CheckFQDNExistsInOtherProjectExcludingSelfParams) (bool, error)
	CheckInternalPortExistsInProject(ctx context.Context, arg CheckInternalPortExistsInProjectParams) (bool, error)
	// Check if internal port exists in project, excluding self (for UpdateNetwork)
	// Internal ports must be unique within a project (containers share pod network interface)
	CheckInternalPortExistsInProjectExcludingSelf(ctx context.Context, arg CheckInternalPortExistsInProjectExcludingSelfParams) (bool, error)
	CountBuildVarsByContainerID(ctx context.Context, containerID uint32) (int64, error)
	CountContainers(ctx context.Context) (int64, error)
	CountContainersByProjectID(ctx context.Context, projectID uint32) (int64, error)
	CountContainersByTemplateID(ctx context.Context, templateID sql.NullInt32) (int64, error)
	CountEnvVarsByContainerID(ctx context.Context, containerID uint32) (int64, error)
	CountMountsByContainerID(ctx context.Context, containerID uint32) (int64, error)
	CountNetworksByContainerID(ctx context.Context, containerID uint32) (int64, error)
	CountSecretsByContainerID(ctx context.Context, containerID uint32) (int64, error)
	// Build Variables CRUD
	CreateBuildVar(ctx context.Context, arg CreateBuildVarParams) (sql.Result, error)
	// Containers CRUD
	CreateContainer(ctx context.Context, arg CreateContainerParams) (sql.Result, error)
	// Environment Variables CRUD
	CreateEnvVar(ctx context.Context, arg CreateEnvVarParams) (sql.Result, error)
	// Volume Mounts CRUD
	CreateMount(ctx context.Context, arg CreateMountParams) (sql.Result, error)
	// Networks CRUD
	CreateNetwork(ctx context.Context, arg CreateNetworkParams) (sql.Result, error)
	// Secrets CRUD
	CreateSecret(ctx context.Context, arg CreateSecretParams) (sql.Result, error)
	DeleteBuildVar(ctx context.Context, arg DeleteBuildVarParams) (sql.Result, error)
	DeleteBuildVarsByContainerID(ctx context.Context, containerID uint32) (sql.Result, error)
	DeleteContainer(ctx context.Context, arg DeleteContainerParams) (sql.Result, error)
	DeleteContainersByProjectID(ctx context.Context, arg DeleteContainersByProjectIDParams) (sql.Result, error)
	DeleteEnvVar(ctx context.Context, arg DeleteEnvVarParams) (sql.Result, error)
	DeleteEnvVarsByContainerID(ctx context.Context, containerID uint32) (sql.Result, error)
	DeleteMount(ctx context.Context, arg DeleteMountParams) (sql.Result, error)
	DeleteMountsByContainerID(ctx context.Context, containerID uint32) (sql.Result, error)
	DeleteNetwork(ctx context.Context, arg DeleteNetworkParams) (sql.Result, error)
	DeleteNetworksByContainerID(ctx context.Context, containerID uint32) (sql.Result, error)
	DeleteSecret(ctx context.Context, arg DeleteSecretParams) (sql.Result, error)
	DeleteSecretsByContainerID(ctx context.Context, containerID uint32) (sql.Result, error)
	ExistsByNameAndProjectID(ctx context.Context, arg ExistsByNameAndProjectIDParams) (bool, error)
	ExistsBySlug(ctx context.Context, slug string) (bool, error)
	ExistsMountByVolume(ctx context.Context, arg ExistsMountByVolumeParams) (bool, error)
	ExistsTemplateByID(ctx context.Context, templateID uint32) (bool, error)
	FindActiveTemplates(ctx context.Context) ([]Template, error)
	// Template Queries
	// Templates are read-only and managed directly in the database by administrators
	FindAllTemplates(ctx context.Context) ([]Template, error)
	FindTemplateByID(ctx context.Context, templateID uint32) (Template, error)
	GetBuildVarByKey(ctx context.Context, arg GetBuildVarByKeyParams) (GetBuildVarByKeyRow, error)
	GetBuildVarsByContainerID(ctx context.Context, containerID uint32) ([]GetBuildVarsByContainerIDRow, error)
	GetContainerByID(ctx context.Context, containerID uint32) (Container, error)
	GetContainerByIDForUpdate(ctx context.Context, containerID uint32) (Container, error)
	GetContainerBySlug(ctx context.Context, slug string) (Container, error)
	GetEnvVarByKey(ctx context.Context, arg GetEnvVarByKeyParams) (EnvVar, error)
	GetEnvVarsByContainerID(ctx context.Context, containerID uint32) ([]EnvVar, error)
	GetMountByVolume(ctx context.Context, arg GetMountByVolumeParams) (Mount, error)
	GetMountsByContainerID(ctx context.Context, containerID uint32) ([]Mount, error)
	GetNetworkByID(ctx context.Context, networkID uint32) (Network, error)
	GetNetworksByContainerID(ctx context.Context, containerID uint32) ([]Network, error)
	GetSecretByKey(ctx context.Context, arg GetSecretByKeyParams) (Secret, error)
	GetSecretsByContainerID(ctx context.Context, containerID uint32) ([]Secret, error)
	GetTotalResourceUsageByProject(ctx context.Context, projectID uint32) (GetTotalResourceUsageByProjectRow, error)
	ListContainerSlugsByProjectIDIncludingDeleted(ctx context.Context, projectID uint32) ([]string, error)
	ListContainers(ctx context.Context, arg ListContainersParams) ([]Container, error)
	ListContainersByProjectID(ctx context.Context, projectID uint32) ([]Container, error)
	// Soft delete a specific network by ID
	// Preserves FQDN ownership for the project
	SoftDeleteNetworkByID(ctx context.Context, arg SoftDeleteNetworkByIDParams) (sql.Result, error)
	// Soft delete all networks when a container is deleted
	// This preserves FQDN ownership tracking even after container deletion
	SoftDeleteNetworksByContainerID(ctx context.Context, arg SoftDeleteNetworksByContainerIDParams) (sql.Result, error)
	UpdateBuildVar(ctx context.Context, arg UpdateBuildVarParams) (sql.Result, error)
	UpdateContainer(ctx context.Context, arg UpdateContainerParams) (sql.Result, error)
	UpdateEnvVar(ctx context.Context, arg UpdateEnvVarParams) (sql.Result, error)
	UpdateNetwork(ctx context.Context, arg UpdateNetworkParams) (sql.Result, error)
	UpdateSecret(ctx context.Context, arg UpdateSecretParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
