// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountContainers(ctx context.Context) (int64, error)
	CountContainersByProjectID(ctx context.Context, projectID uint32) (int64, error)
	CountContainersByTemplateID(ctx context.Context, templateID sql.NullInt32) (int64, error)
	CountEnvVarsByContainerID(ctx context.Context, containerID uint32) (int64, error)
	CountMountsByContainerID(ctx context.Context, containerID uint32) (int64, error)
	CountNetworksByContainerID(ctx context.Context, containerID uint32) (int64, error)
	CountSecretsByContainerID(ctx context.Context, containerID uint32) (int64, error)
	// Containers CRUD
	CreateContainer(ctx context.Context, arg CreateContainerParams) (sql.Result, error)
	// Environment Variables CRUD
	CreateEnvVar(ctx context.Context, arg CreateEnvVarParams) (sql.Result, error)
	// Volume Mounts CRUD
	CreateMount(ctx context.Context, arg CreateMountParams) (sql.Result, error)
	// Networks CRUD
	CreateNetwork(ctx context.Context, arg CreateNetworkParams) (sql.Result, error)
	// Secrets CRUD
	CreateSecret(ctx context.Context, arg CreateSecretParams) (sql.Result, error)
	DeleteContainer(ctx context.Context, arg DeleteContainerParams) (sql.Result, error)
	DeleteContainersByProjectID(ctx context.Context, arg DeleteContainersByProjectIDParams) (sql.Result, error)
	DeleteEnvVar(ctx context.Context, arg DeleteEnvVarParams) (sql.Result, error)
	DeleteEnvVarsByContainerID(ctx context.Context, containerID uint32) (sql.Result, error)
	DeleteMount(ctx context.Context, arg DeleteMountParams) (sql.Result, error)
	DeleteMountsByContainerID(ctx context.Context, containerID uint32) (sql.Result, error)
	DeleteNetwork(ctx context.Context, networkID uint32) (sql.Result, error)
	DeleteNetworksByContainerID(ctx context.Context, containerID uint32) (sql.Result, error)
	DeleteSecret(ctx context.Context, arg DeleteSecretParams) (sql.Result, error)
	DeleteSecretsByContainerID(ctx context.Context, containerID uint32) (sql.Result, error)
	ExistsByNameAndProjectID(ctx context.Context, arg ExistsByNameAndProjectIDParams) (bool, error)
	ExistsBySlug(ctx context.Context, arg ExistsBySlugParams) (bool, error)
	ExistsMountByVolume(ctx context.Context, arg ExistsMountByVolumeParams) (bool, error)
	ExistsTemplateByID(ctx context.Context, templateID uint32) (bool, error)
	FindActiveTemplates(ctx context.Context) ([]Template, error)
	// Template Queries
	// Templates are read-only and managed directly in the database by administrators
	FindAllTemplates(ctx context.Context) ([]Template, error)
	FindTemplateByID(ctx context.Context, templateID uint32) (Template, error)
	GetContainerByID(ctx context.Context, containerID uint32) (Container, error)
	GetContainerByIDForUpdate(ctx context.Context, containerID uint32) (Container, error)
	GetContainerBySlug(ctx context.Context, arg GetContainerBySlugParams) (Container, error)
	GetEnvVarByKey(ctx context.Context, arg GetEnvVarByKeyParams) (EnvVar, error)
	GetEnvVarsByContainerID(ctx context.Context, containerID uint32) ([]EnvVar, error)
	GetMountByVolume(ctx context.Context, arg GetMountByVolumeParams) (Mount, error)
	GetMountsByContainerID(ctx context.Context, containerID uint32) ([]Mount, error)
	GetNetworkByID(ctx context.Context, networkID uint32) (Network, error)
	GetNetworksByContainerID(ctx context.Context, containerID uint32) ([]Network, error)
	GetSecretByKey(ctx context.Context, arg GetSecretByKeyParams) (GetSecretByKeyRow, error)
	GetSecretsByContainerID(ctx context.Context, containerID uint32) ([]GetSecretsByContainerIDRow, error)
	GetTotalResourceUsageByProject(ctx context.Context, projectID uint32) (GetTotalResourceUsageByProjectRow, error)
	ListContainers(ctx context.Context, arg ListContainersParams) ([]Container, error)
	ListContainersByProjectID(ctx context.Context, projectID uint32) ([]Container, error)
	UpdateContainer(ctx context.Context, arg UpdateContainerParams) (sql.Result, error)
	UpdateEnvVar(ctx context.Context, arg UpdateEnvVarParams) (sql.Result, error)
	UpdateNetwork(ctx context.Context, arg UpdateNetworkParams) (sql.Result, error)
	UpdateSecret(ctx context.Context, arg UpdateSecretParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
