// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: secrets.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countSecretsByContainerID = `-- name: CountSecretsByContainerID :one
SELECT COUNT(*) as total FROM SECRETS WHERE container_id = ?
`

func (q *Queries) CountSecretsByContainerID(ctx context.Context, containerID uint32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSecretsByContainerID, containerID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createSecret = `-- name: CreateSecret :execresult

INSERT INTO SECRETS (
    container_id, ` + "`" + `key` + "`" + `, value,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?)
`

type CreateSecretParams struct {
	ContainerID uint32         `json:"container_id"`
	Key         string         `json:"key"`
	Value       sql.NullString `json:"value"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

// Secrets CRUD
func (q *Queries) CreateSecret(ctx context.Context, arg CreateSecretParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSecret,
		arg.ContainerID,
		arg.Key,
		arg.Value,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const deleteSecret = `-- name: DeleteSecret :execresult
DELETE FROM SECRETS
WHERE container_id = ? AND ` + "`" + `key` + "`" + ` = ?
`

type DeleteSecretParams struct {
	ContainerID uint32 `json:"container_id"`
	Key         string `json:"key"`
}

func (q *Queries) DeleteSecret(ctx context.Context, arg DeleteSecretParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteSecret, arg.ContainerID, arg.Key)
}

const deleteSecretsByContainerID = `-- name: DeleteSecretsByContainerID :execresult
DELETE FROM SECRETS
WHERE container_id = ?
`

func (q *Queries) DeleteSecretsByContainerID(ctx context.Context, containerID uint32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteSecretsByContainerID, containerID)
}

const getSecretByKey = `-- name: GetSecretByKey :one
SELECT
    secret_id, container_id, ` + "`" + `key` + "`" + `, value,
    created_at, updated_at
FROM SECRETS
WHERE container_id = ? AND ` + "`" + `key` + "`" + ` = ?
`

type GetSecretByKeyParams struct {
	ContainerID uint32 `json:"container_id"`
	Key         string `json:"key"`
}

type GetSecretByKeyRow struct {
	SecretID    uint32         `json:"secret_id"`
	ContainerID uint32         `json:"container_id"`
	Key         string         `json:"key"`
	Value       sql.NullString `json:"value"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetSecretByKey(ctx context.Context, arg GetSecretByKeyParams) (GetSecretByKeyRow, error) {
	row := q.db.QueryRowContext(ctx, getSecretByKey, arg.ContainerID, arg.Key)
	var i GetSecretByKeyRow
	err := row.Scan(
		&i.SecretID,
		&i.ContainerID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSecretsByContainerID = `-- name: GetSecretsByContainerID :many
SELECT
    secret_id, container_id, ` + "`" + `key` + "`" + `, value,
    created_at, updated_at
FROM SECRETS
WHERE container_id = ?
ORDER BY ` + "`" + `key` + "`" + ` ASC
`

type GetSecretsByContainerIDRow struct {
	SecretID    uint32         `json:"secret_id"`
	ContainerID uint32         `json:"container_id"`
	Key         string         `json:"key"`
	Value       sql.NullString `json:"value"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetSecretsByContainerID(ctx context.Context, containerID uint32) ([]GetSecretsByContainerIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getSecretsByContainerID, containerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSecretsByContainerIDRow{}
	for rows.Next() {
		var i GetSecretsByContainerIDRow
		if err := rows.Scan(
			&i.SecretID,
			&i.ContainerID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSecret = `-- name: UpdateSecret :execresult
UPDATE SECRETS SET
    value = ?,
    updated_at = ?
WHERE container_id = ? AND ` + "`" + `key` + "`" + ` = ?
`

type UpdateSecretParams struct {
	Value       sql.NullString `json:"value"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	ContainerID uint32         `json:"container_id"`
	Key         string         `json:"key"`
}

func (q *Queries) UpdateSecret(ctx context.Context, arg UpdateSecretParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateSecret,
		arg.Value,
		arg.UpdatedAt,
		arg.ContainerID,
		arg.Key,
	)
}
