// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: templates.sql

package sqlc

import (
	"context"
)

const existsTemplateByID = `-- name: ExistsTemplateByID :one
SELECT EXISTS(SELECT 1 FROM TEMPLATES WHERE template_id = ?) AS template_exists
`

func (q *Queries) ExistsTemplateByID(ctx context.Context, templateID uint32) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsTemplateByID, templateID)
	var template_exists bool
	err := row.Scan(&template_exists)
	return template_exists, err
}

const findActiveTemplates = `-- name: FindActiveTemplates :many
SELECT template_id, name, template_body, template_config, status, created_at, updated_at
FROM TEMPLATES
WHERE status = 'active'
ORDER BY template_id
`

func (q *Queries) FindActiveTemplates(ctx context.Context) ([]Template, error) {
	rows, err := q.db.QueryContext(ctx, findActiveTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.TemplateID,
			&i.Name,
			&i.TemplateBody,
			&i.TemplateConfig,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllTemplates = `-- name: FindAllTemplates :many

SELECT template_id, name, template_body, template_config, status, created_at, updated_at
FROM TEMPLATES
ORDER BY template_id
`

// Template Queries
// Templates are read-only and managed directly in the database by administrators
func (q *Queries) FindAllTemplates(ctx context.Context) ([]Template, error) {
	rows, err := q.db.QueryContext(ctx, findAllTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.TemplateID,
			&i.Name,
			&i.TemplateBody,
			&i.TemplateConfig,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findTemplateByID = `-- name: FindTemplateByID :one
SELECT template_id, name, template_body, template_config, status, created_at, updated_at
FROM TEMPLATES
WHERE template_id = ?
`

func (q *Queries) FindTemplateByID(ctx context.Context, templateID uint32) (Template, error) {
	row := q.db.QueryRowContext(ctx, findTemplateByID, templateID)
	var i Template
	err := row.Scan(
		&i.TemplateID,
		&i.Name,
		&i.TemplateBody,
		&i.TemplateConfig,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
