// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: build_histories.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createBuildHistory = `-- name: CreateBuildHistory :execresult
INSERT INTO ` + "`" + `BUILD_HISTORY` + "`" + ` (
    ` + "`" + `container_id` + "`" + `,
    ` + "`" + `status` + "`" + `,
    ` + "`" + `summary` + "`" + `,
    ` + "`" + `tekton_event_id` + "`" + `,
    ` + "`" + `tekton_pipeline_run_name` + "`" + `,
    ` + "`" + `git_commit_hash` + "`" + `,
    ` + "`" + `created_at` + "`" + `,
    ` + "`" + `started_at` + "`" + `,
    ` + "`" + `finished_at` + "`" + `
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateBuildHistoryParams struct {
	ContainerID           uint32             `json:"container_id"`
	Status                BuildHistoryStatus `json:"status"`
	Summary               sql.NullString     `json:"summary"`
	TektonEventID         sql.NullString     `json:"tekton_event_id"`
	TektonPipelineRunName sql.NullString     `json:"tekton_pipeline_run_name"`
	GitCommitHash         sql.NullString     `json:"git_commit_hash"`
	CreatedAt             time.Time          `json:"created_at"`
	StartedAt             sql.NullTime       `json:"started_at"`
	FinishedAt            sql.NullTime       `json:"finished_at"`
}

func (q *Queries) CreateBuildHistory(ctx context.Context, arg CreateBuildHistoryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createBuildHistory,
		arg.ContainerID,
		arg.Status,
		arg.Summary,
		arg.TektonEventID,
		arg.TektonPipelineRunName,
		arg.GitCommitHash,
		arg.CreatedAt,
		arg.StartedAt,
		arg.FinishedAt,
	)
}

const findActiveBuildHistoriesByContainerID = `-- name: FindActiveBuildHistoriesByContainerID :many
SELECT
    ` + "`" + `build_history_id` + "`" + `,
    ` + "`" + `container_id` + "`" + `,
    ` + "`" + `status` + "`" + `,
    ` + "`" + `summary` + "`" + `,
    ` + "`" + `tekton_event_id` + "`" + `,
    ` + "`" + `tekton_pipeline_run_name` + "`" + `,
    ` + "`" + `git_commit_hash` + "`" + `,
    ` + "`" + `created_at` + "`" + `,
    ` + "`" + `started_at` + "`" + `,
    ` + "`" + `finished_at` + "`" + `
FROM ` + "`" + `BUILD_HISTORY` + "`" + `
WHERE ` + "`" + `container_id` + "`" + ` = ?
AND ` + "`" + `status` + "`" + ` IN ('untracked', 'running', 'backend_tracking_lost')
ORDER BY ` + "`" + `created_at` + "`" + ` DESC, ` + "`" + `build_history_id` + "`" + ` DESC
`

// Returns all non-completed build histories for a container.
// Includes: untracked, running, backend_tracking_lost (recoverable states)
// Excludes: success, failed, cancelled, skipped, backend_trigger_failed, backend_tracking_failed (terminal states)
func (q *Queries) FindActiveBuildHistoriesByContainerID(ctx context.Context, containerID uint32) ([]BuildHistory, error) {
	rows, err := q.db.QueryContext(ctx, findActiveBuildHistoriesByContainerID, containerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BuildHistory{}
	for rows.Next() {
		var i BuildHistory
		if err := rows.Scan(
			&i.BuildHistoryID,
			&i.ContainerID,
			&i.Status,
			&i.Summary,
			&i.TektonEventID,
			&i.TektonPipelineRunName,
			&i.GitCommitHash,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findBuildHistoriesByContainerID = `-- name: FindBuildHistoriesByContainerID :many
SELECT
    ` + "`" + `build_history_id` + "`" + `,
    ` + "`" + `container_id` + "`" + `,
    ` + "`" + `status` + "`" + `,
    ` + "`" + `summary` + "`" + `,
    ` + "`" + `tekton_event_id` + "`" + `,
    ` + "`" + `tekton_pipeline_run_name` + "`" + `,
    ` + "`" + `git_commit_hash` + "`" + `,
    ` + "`" + `created_at` + "`" + `,
    ` + "`" + `started_at` + "`" + `,
    ` + "`" + `finished_at` + "`" + `
FROM ` + "`" + `BUILD_HISTORY` + "`" + `
WHERE ` + "`" + `container_id` + "`" + ` = ?
ORDER BY ` + "`" + `created_at` + "`" + ` DESC, ` + "`" + `build_history_id` + "`" + ` DESC
LIMIT ? OFFSET ?
`

type FindBuildHistoriesByContainerIDParams struct {
	ContainerID uint32 `json:"container_id"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) FindBuildHistoriesByContainerID(ctx context.Context, arg FindBuildHistoriesByContainerIDParams) ([]BuildHistory, error) {
	rows, err := q.db.QueryContext(ctx, findBuildHistoriesByContainerID, arg.ContainerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BuildHistory{}
	for rows.Next() {
		var i BuildHistory
		if err := rows.Scan(
			&i.BuildHistoryID,
			&i.ContainerID,
			&i.Status,
			&i.Summary,
			&i.TektonEventID,
			&i.TektonPipelineRunName,
			&i.GitCommitHash,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findBuildHistoryByID = `-- name: FindBuildHistoryByID :one
SELECT
    ` + "`" + `build_history_id` + "`" + `,
    ` + "`" + `container_id` + "`" + `,
    ` + "`" + `status` + "`" + `,
    ` + "`" + `summary` + "`" + `,
    ` + "`" + `tekton_event_id` + "`" + `,
    ` + "`" + `tekton_pipeline_run_name` + "`" + `,
    ` + "`" + `git_commit_hash` + "`" + `,
    ` + "`" + `created_at` + "`" + `,
    ` + "`" + `started_at` + "`" + `,
    ` + "`" + `finished_at` + "`" + `
FROM ` + "`" + `BUILD_HISTORY` + "`" + `
WHERE ` + "`" + `build_history_id` + "`" + ` = ?
LIMIT 1
`

func (q *Queries) FindBuildHistoryByID(ctx context.Context, buildHistoryID uint32) (BuildHistory, error) {
	row := q.db.QueryRowContext(ctx, findBuildHistoryByID, buildHistoryID)
	var i BuildHistory
	err := row.Scan(
		&i.BuildHistoryID,
		&i.ContainerID,
		&i.Status,
		&i.Summary,
		&i.TektonEventID,
		&i.TektonPipelineRunName,
		&i.GitCommitHash,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const findBuildHistoryByTektonPipelineRunName = `-- name: FindBuildHistoryByTektonPipelineRunName :one
SELECT
    ` + "`" + `build_history_id` + "`" + `,
    ` + "`" + `container_id` + "`" + `,
    ` + "`" + `status` + "`" + `,
    ` + "`" + `summary` + "`" + `,
    ` + "`" + `tekton_event_id` + "`" + `,
    ` + "`" + `tekton_pipeline_run_name` + "`" + `,
    ` + "`" + `git_commit_hash` + "`" + `,
    ` + "`" + `created_at` + "`" + `,
    ` + "`" + `started_at` + "`" + `,
    ` + "`" + `finished_at` + "`" + `
FROM ` + "`" + `BUILD_HISTORY` + "`" + `
WHERE ` + "`" + `tekton_pipeline_run_name` + "`" + ` = ?
LIMIT 1
`

func (q *Queries) FindBuildHistoryByTektonPipelineRunName(ctx context.Context, tektonPipelineRunName sql.NullString) (BuildHistory, error) {
	row := q.db.QueryRowContext(ctx, findBuildHistoryByTektonPipelineRunName, tektonPipelineRunName)
	var i BuildHistory
	err := row.Scan(
		&i.BuildHistoryID,
		&i.ContainerID,
		&i.Status,
		&i.Summary,
		&i.TektonEventID,
		&i.TektonPipelineRunName,
		&i.GitCommitHash,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const findLatestBuildHistoryByContainerID = `-- name: FindLatestBuildHistoryByContainerID :one
SELECT
    ` + "`" + `build_history_id` + "`" + `,
    ` + "`" + `container_id` + "`" + `,
    ` + "`" + `status` + "`" + `,
    ` + "`" + `summary` + "`" + `,
    ` + "`" + `tekton_event_id` + "`" + `,
    ` + "`" + `tekton_pipeline_run_name` + "`" + `,
    ` + "`" + `git_commit_hash` + "`" + `,
    ` + "`" + `created_at` + "`" + `,
    ` + "`" + `started_at` + "`" + `,
    ` + "`" + `finished_at` + "`" + `
FROM ` + "`" + `BUILD_HISTORY` + "`" + `
WHERE ` + "`" + `container_id` + "`" + ` = ?
ORDER BY ` + "`" + `created_at` + "`" + ` DESC, ` + "`" + `build_history_id` + "`" + ` DESC
LIMIT 1
`

func (q *Queries) FindLatestBuildHistoryByContainerID(ctx context.Context, containerID uint32) (BuildHistory, error) {
	row := q.db.QueryRowContext(ctx, findLatestBuildHistoryByContainerID, containerID)
	var i BuildHistory
	err := row.Scan(
		&i.BuildHistoryID,
		&i.ContainerID,
		&i.Status,
		&i.Summary,
		&i.TektonEventID,
		&i.TektonPipelineRunName,
		&i.GitCommitHash,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const updateBuildHistory = `-- name: UpdateBuildHistory :execresult
UPDATE ` + "`" + `BUILD_HISTORY` + "`" + `
SET
    ` + "`" + `status` + "`" + ` = ?,
    ` + "`" + `summary` + "`" + ` = ?,
    ` + "`" + `tekton_event_id` + "`" + ` = ?,
    ` + "`" + `tekton_pipeline_run_name` + "`" + ` = ?,
    ` + "`" + `git_commit_hash` + "`" + ` = ?,
    ` + "`" + `started_at` + "`" + ` = ?,
    ` + "`" + `finished_at` + "`" + ` = ?
WHERE
    ` + "`" + `build_history_id` + "`" + ` = ?
`

type UpdateBuildHistoryParams struct {
	Status                BuildHistoryStatus `json:"status"`
	Summary               sql.NullString     `json:"summary"`
	TektonEventID         sql.NullString     `json:"tekton_event_id"`
	TektonPipelineRunName sql.NullString     `json:"tekton_pipeline_run_name"`
	GitCommitHash         sql.NullString     `json:"git_commit_hash"`
	StartedAt             sql.NullTime       `json:"started_at"`
	FinishedAt            sql.NullTime       `json:"finished_at"`
	BuildHistoryID        uint32             `json:"build_history_id"`
}

func (q *Queries) UpdateBuildHistory(ctx context.Context, arg UpdateBuildHistoryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateBuildHistory,
		arg.Status,
		arg.Summary,
		arg.TektonEventID,
		arg.TektonPipelineRunName,
		arg.GitCommitHash,
		arg.StartedAt,
		arg.FinishedAt,
		arg.BuildHistoryID,
	)
}
