// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployments.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createDeployment = `-- name: CreateDeployment :execresult
INSERT INTO ` + "`" + `DEPLOYMENTS` + "`" + ` (
    ` + "`" + `project_id` + "`" + `,
    ` + "`" + `status` + "`" + `,
    ` + "`" + `summary` + "`" + `,
    ` + "`" + `tekton_event_id` + "`" + `,
    ` + "`" + `tekton_pipeline_run_name` + "`" + `,
    ` + "`" + `created_at` + "`" + `,
    ` + "`" + `started_at` + "`" + `,
    ` + "`" + `finished_at` + "`" + `
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateDeploymentParams struct {
	ProjectID             uint32            `json:"project_id"`
	Status                DeploymentsStatus `json:"status"`
	Summary               sql.NullString    `json:"summary"`
	TektonEventID         sql.NullString    `json:"tekton_event_id"`
	TektonPipelineRunName sql.NullString    `json:"tekton_pipeline_run_name"`
	CreatedAt             time.Time         `json:"created_at"`
	StartedAt             sql.NullTime      `json:"started_at"`
	FinishedAt            sql.NullTime      `json:"finished_at"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createDeployment,
		arg.ProjectID,
		arg.Status,
		arg.Summary,
		arg.TektonEventID,
		arg.TektonPipelineRunName,
		arg.CreatedAt,
		arg.StartedAt,
		arg.FinishedAt,
	)
}

const findActiveDeploymentsByProjectID = `-- name: FindActiveDeploymentsByProjectID :many
SELECT
    ` + "`" + `deployment_id` + "`" + `,
    ` + "`" + `project_id` + "`" + `,
    ` + "`" + `status` + "`" + `,
    ` + "`" + `summary` + "`" + `,
    ` + "`" + `tekton_event_id` + "`" + `,
    ` + "`" + `tekton_pipeline_run_name` + "`" + `,
    ` + "`" + `created_at` + "`" + `,
    ` + "`" + `started_at` + "`" + `,
    ` + "`" + `finished_at` + "`" + `
FROM ` + "`" + `DEPLOYMENTS` + "`" + `
WHERE ` + "`" + `project_id` + "`" + ` = ?
AND ` + "`" + `status` + "`" + ` IN ('untracked', 'running')
ORDER BY ` + "`" + `created_at` + "`" + ` DESC, ` + "`" + `deployment_id` + "`" + ` DESC
`

type FindActiveDeploymentsByProjectIDRow struct {
	DeploymentID          uint32            `json:"deployment_id"`
	ProjectID             uint32            `json:"project_id"`
	Status                DeploymentsStatus `json:"status"`
	Summary               sql.NullString    `json:"summary"`
	TektonEventID         sql.NullString    `json:"tekton_event_id"`
	TektonPipelineRunName sql.NullString    `json:"tekton_pipeline_run_name"`
	CreatedAt             time.Time         `json:"created_at"`
	StartedAt             sql.NullTime      `json:"started_at"`
	FinishedAt            sql.NullTime      `json:"finished_at"`
}

func (q *Queries) FindActiveDeploymentsByProjectID(ctx context.Context, projectID uint32) ([]FindActiveDeploymentsByProjectIDRow, error) {
	rows, err := q.db.QueryContext(ctx, findActiveDeploymentsByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindActiveDeploymentsByProjectIDRow{}
	for rows.Next() {
		var i FindActiveDeploymentsByProjectIDRow
		if err := rows.Scan(
			&i.DeploymentID,
			&i.ProjectID,
			&i.Status,
			&i.Summary,
			&i.TektonEventID,
			&i.TektonPipelineRunName,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findDeploymentByID = `-- name: FindDeploymentByID :one
SELECT
    ` + "`" + `deployment_id` + "`" + `,
    ` + "`" + `project_id` + "`" + `,
    ` + "`" + `status` + "`" + `,
    ` + "`" + `summary` + "`" + `,
    ` + "`" + `tekton_event_id` + "`" + `,
    ` + "`" + `tekton_pipeline_run_name` + "`" + `,
    ` + "`" + `created_at` + "`" + `,
    ` + "`" + `started_at` + "`" + `,
    ` + "`" + `finished_at` + "`" + `
FROM ` + "`" + `DEPLOYMENTS` + "`" + `
WHERE ` + "`" + `deployment_id` + "`" + ` = ?
LIMIT 1
`

type FindDeploymentByIDRow struct {
	DeploymentID          uint32            `json:"deployment_id"`
	ProjectID             uint32            `json:"project_id"`
	Status                DeploymentsStatus `json:"status"`
	Summary               sql.NullString    `json:"summary"`
	TektonEventID         sql.NullString    `json:"tekton_event_id"`
	TektonPipelineRunName sql.NullString    `json:"tekton_pipeline_run_name"`
	CreatedAt             time.Time         `json:"created_at"`
	StartedAt             sql.NullTime      `json:"started_at"`
	FinishedAt            sql.NullTime      `json:"finished_at"`
}

func (q *Queries) FindDeploymentByID(ctx context.Context, deploymentID uint32) (FindDeploymentByIDRow, error) {
	row := q.db.QueryRowContext(ctx, findDeploymentByID, deploymentID)
	var i FindDeploymentByIDRow
	err := row.Scan(
		&i.DeploymentID,
		&i.ProjectID,
		&i.Status,
		&i.Summary,
		&i.TektonEventID,
		&i.TektonPipelineRunName,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const findDeploymentByTektonPipelineRunName = `-- name: FindDeploymentByTektonPipelineRunName :one
SELECT
    ` + "`" + `deployment_id` + "`" + `,
    ` + "`" + `project_id` + "`" + `,
    ` + "`" + `status` + "`" + `,
    ` + "`" + `summary` + "`" + `,
    ` + "`" + `tekton_event_id` + "`" + `,
    ` + "`" + `tekton_pipeline_run_name` + "`" + `,
    ` + "`" + `created_at` + "`" + `,
    ` + "`" + `started_at` + "`" + `,
    ` + "`" + `finished_at` + "`" + `
FROM ` + "`" + `DEPLOYMENTS` + "`" + `
WHERE ` + "`" + `tekton_pipeline_run_name` + "`" + ` = ?
LIMIT 1
`

type FindDeploymentByTektonPipelineRunNameRow struct {
	DeploymentID          uint32            `json:"deployment_id"`
	ProjectID             uint32            `json:"project_id"`
	Status                DeploymentsStatus `json:"status"`
	Summary               sql.NullString    `json:"summary"`
	TektonEventID         sql.NullString    `json:"tekton_event_id"`
	TektonPipelineRunName sql.NullString    `json:"tekton_pipeline_run_name"`
	CreatedAt             time.Time         `json:"created_at"`
	StartedAt             sql.NullTime      `json:"started_at"`
	FinishedAt            sql.NullTime      `json:"finished_at"`
}

func (q *Queries) FindDeploymentByTektonPipelineRunName(ctx context.Context, tektonPipelineRunName sql.NullString) (FindDeploymentByTektonPipelineRunNameRow, error) {
	row := q.db.QueryRowContext(ctx, findDeploymentByTektonPipelineRunName, tektonPipelineRunName)
	var i FindDeploymentByTektonPipelineRunNameRow
	err := row.Scan(
		&i.DeploymentID,
		&i.ProjectID,
		&i.Status,
		&i.Summary,
		&i.TektonEventID,
		&i.TektonPipelineRunName,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const findDeploymentsByProjectID = `-- name: FindDeploymentsByProjectID :many
SELECT
    ` + "`" + `deployment_id` + "`" + `,
    ` + "`" + `project_id` + "`" + `,
    ` + "`" + `status` + "`" + `,
    ` + "`" + `summary` + "`" + `,
    ` + "`" + `tekton_event_id` + "`" + `,
    ` + "`" + `tekton_pipeline_run_name` + "`" + `,
    ` + "`" + `created_at` + "`" + `,
    ` + "`" + `started_at` + "`" + `,
    ` + "`" + `finished_at` + "`" + `
FROM ` + "`" + `DEPLOYMENTS` + "`" + `
WHERE ` + "`" + `project_id` + "`" + ` = ?
ORDER BY ` + "`" + `created_at` + "`" + ` DESC, ` + "`" + `deployment_id` + "`" + ` DESC
LIMIT ? OFFSET ?
`

type FindDeploymentsByProjectIDParams struct {
	ProjectID uint32 `json:"project_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

type FindDeploymentsByProjectIDRow struct {
	DeploymentID          uint32            `json:"deployment_id"`
	ProjectID             uint32            `json:"project_id"`
	Status                DeploymentsStatus `json:"status"`
	Summary               sql.NullString    `json:"summary"`
	TektonEventID         sql.NullString    `json:"tekton_event_id"`
	TektonPipelineRunName sql.NullString    `json:"tekton_pipeline_run_name"`
	CreatedAt             time.Time         `json:"created_at"`
	StartedAt             sql.NullTime      `json:"started_at"`
	FinishedAt            sql.NullTime      `json:"finished_at"`
}

func (q *Queries) FindDeploymentsByProjectID(ctx context.Context, arg FindDeploymentsByProjectIDParams) ([]FindDeploymentsByProjectIDRow, error) {
	rows, err := q.db.QueryContext(ctx, findDeploymentsByProjectID, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindDeploymentsByProjectIDRow{}
	for rows.Next() {
		var i FindDeploymentsByProjectIDRow
		if err := rows.Scan(
			&i.DeploymentID,
			&i.ProjectID,
			&i.Status,
			&i.Summary,
			&i.TektonEventID,
			&i.TektonPipelineRunName,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findLatestDeploymentByProjectID = `-- name: FindLatestDeploymentByProjectID :one
SELECT
    ` + "`" + `deployment_id` + "`" + `,
    ` + "`" + `project_id` + "`" + `,
    ` + "`" + `status` + "`" + `,
    ` + "`" + `summary` + "`" + `,
    ` + "`" + `tekton_event_id` + "`" + `,
    ` + "`" + `tekton_pipeline_run_name` + "`" + `,
    ` + "`" + `created_at` + "`" + `,
    ` + "`" + `started_at` + "`" + `,
    ` + "`" + `finished_at` + "`" + `
FROM ` + "`" + `DEPLOYMENTS` + "`" + `
WHERE ` + "`" + `project_id` + "`" + ` = ?
ORDER BY ` + "`" + `created_at` + "`" + ` DESC, ` + "`" + `deployment_id` + "`" + ` DESC
LIMIT 1
`

type FindLatestDeploymentByProjectIDRow struct {
	DeploymentID          uint32            `json:"deployment_id"`
	ProjectID             uint32            `json:"project_id"`
	Status                DeploymentsStatus `json:"status"`
	Summary               sql.NullString    `json:"summary"`
	TektonEventID         sql.NullString    `json:"tekton_event_id"`
	TektonPipelineRunName sql.NullString    `json:"tekton_pipeline_run_name"`
	CreatedAt             time.Time         `json:"created_at"`
	StartedAt             sql.NullTime      `json:"started_at"`
	FinishedAt            sql.NullTime      `json:"finished_at"`
}

func (q *Queries) FindLatestDeploymentByProjectID(ctx context.Context, projectID uint32) (FindLatestDeploymentByProjectIDRow, error) {
	row := q.db.QueryRowContext(ctx, findLatestDeploymentByProjectID, projectID)
	var i FindLatestDeploymentByProjectIDRow
	err := row.Scan(
		&i.DeploymentID,
		&i.ProjectID,
		&i.Status,
		&i.Summary,
		&i.TektonEventID,
		&i.TektonPipelineRunName,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const updateDeployment = `-- name: UpdateDeployment :execresult
UPDATE ` + "`" + `DEPLOYMENTS` + "`" + `
SET
    ` + "`" + `status` + "`" + ` = ?,
    ` + "`" + `summary` + "`" + ` = ?,
    ` + "`" + `tekton_event_id` + "`" + ` = ?,
    ` + "`" + `tekton_pipeline_run_name` + "`" + ` = ?,
    ` + "`" + `started_at` + "`" + ` = ?,
    ` + "`" + `finished_at` + "`" + ` = ?
WHERE
    ` + "`" + `deployment_id` + "`" + ` = ?
`

type UpdateDeploymentParams struct {
	Status                DeploymentsStatus `json:"status"`
	Summary               sql.NullString    `json:"summary"`
	TektonEventID         sql.NullString    `json:"tekton_event_id"`
	TektonPipelineRunName sql.NullString    `json:"tekton_pipeline_run_name"`
	StartedAt             sql.NullTime      `json:"started_at"`
	FinishedAt            sql.NullTime      `json:"finished_at"`
	DeploymentID          uint32            `json:"deployment_id"`
}

func (q *Queries) UpdateDeployment(ctx context.Context, arg UpdateDeploymentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateDeployment,
		arg.Status,
		arg.Summary,
		arg.TektonEventID,
		arg.TektonPipelineRunName,
		arg.StartedAt,
		arg.FinishedAt,
		arg.DeploymentID,
	)
}
