// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_locks.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const acquireOrUpdateLock = `-- name: AcquireOrUpdateLock :execresult
INSERT INTO DEPLOYMENT_LOCKS (
    project_id, token, expires_at
) VALUES (?, 1, ?)
ON DUPLICATE KEY UPDATE
    token = IF(expires_at <= NOW(), token + 1, token),
    expires_at = IF(expires_at <= NOW(), VALUES(expires_at), expires_at)
`

type AcquireOrUpdateLockParams struct {
	ProjectID uint32    `json:"project_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

// Atomically acquire a new lock or update an expired lock
// Returns RowsAffected: 1 (INSERT new), 2 (UPDATE expired), 0 (active lock exists)
func (q *Queries) AcquireOrUpdateLock(ctx context.Context, arg AcquireOrUpdateLockParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, acquireOrUpdateLock, arg.ProjectID, arg.ExpiresAt)
}

const getDeploymentLock = `-- name: GetDeploymentLock :one

SELECT
    project_id, token, expires_at
FROM DEPLOYMENT_LOCKS
WHERE project_id = ?
`

// Deployment Locks CRUD
func (q *Queries) GetDeploymentLock(ctx context.Context, projectID uint32) (DeploymentLock, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentLock, projectID)
	var i DeploymentLock
	err := row.Scan(&i.ProjectID, &i.Token, &i.ExpiresAt)
	return i, err
}

const releaseDeploymentLock = `-- name: ReleaseDeploymentLock :execresult
UPDATE DEPLOYMENT_LOCKS SET
    expires_at = NOW()
WHERE project_id = ? AND token = ?
`

type ReleaseDeploymentLockParams struct {
	ProjectID uint32 `json:"project_id"`
	Token     uint64 `json:"token"`
}

func (q *Queries) ReleaseDeploymentLock(ctx context.Context, arg ReleaseDeploymentLockParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, releaseDeploymentLock, arg.ProjectID, arg.Token)
}

const renewDeploymentLock = `-- name: RenewDeploymentLock :execresult
UPDATE DEPLOYMENT_LOCKS SET
    expires_at = ?
WHERE project_id = ? AND token = ? AND expires_at > NOW()
`

type RenewDeploymentLockParams struct {
	ExpiresAt time.Time `json:"expires_at"`
	ProjectID uint32    `json:"project_id"`
	Token     uint64    `json:"token"`
}

func (q *Queries) RenewDeploymentLock(ctx context.Context, arg RenewDeploymentLockParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, renewDeploymentLock, arg.ExpiresAt, arg.ProjectID, arg.Token)
}
