// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployments.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createDeployment = `-- name: CreateDeployment :execresult
INSERT INTO ` + "`" + `DEPLOYMENTS` + "`" + ` (
    ` + "`" + `project_id` + "`" + `,
    ` + "`" + `status` + "`" + `,
    ` + "`" + `summary` + "`" + `,
    ` + "`" + `tekton_ref` + "`" + `,
    ` + "`" + `created_at` + "`" + `,
    ` + "`" + `started_at` + "`" + `,
    ` + "`" + `finished_at` + "`" + `
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
`

type CreateDeploymentParams struct {
	ProjectID  uint32            `json:"project_id"`
	Status     DeploymentsStatus `json:"status"`
	Summary    sql.NullString    `json:"summary"`
	TektonRef  sql.NullString    `json:"tekton_ref"`
	CreatedAt  time.Time         `json:"created_at"`
	StartedAt  sql.NullTime      `json:"started_at"`
	FinishedAt sql.NullTime      `json:"finished_at"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createDeployment,
		arg.ProjectID,
		arg.Status,
		arg.Summary,
		arg.TektonRef,
		arg.CreatedAt,
		arg.StartedAt,
		arg.FinishedAt,
	)
}

const findDeploymentByID = `-- name: FindDeploymentByID :one
SELECT
    ` + "`" + `deployment_id` + "`" + `,
    ` + "`" + `project_id` + "`" + `,
    ` + "`" + `status` + "`" + `,
    ` + "`" + `summary` + "`" + `,
    ` + "`" + `tekton_ref` + "`" + `,
    ` + "`" + `created_at` + "`" + `,
    ` + "`" + `started_at` + "`" + `,
    ` + "`" + `finished_at` + "`" + `
FROM ` + "`" + `DEPLOYMENTS` + "`" + `
WHERE ` + "`" + `deployment_id` + "`" + ` = ?
LIMIT 1
`

func (q *Queries) FindDeploymentByID(ctx context.Context, deploymentID uint32) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, findDeploymentByID, deploymentID)
	var i Deployment
	err := row.Scan(
		&i.DeploymentID,
		&i.ProjectID,
		&i.Status,
		&i.Summary,
		&i.TektonRef,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const findDeploymentsByProjectID = `-- name: FindDeploymentsByProjectID :many
SELECT
    ` + "`" + `deployment_id` + "`" + `,
    ` + "`" + `project_id` + "`" + `,
    ` + "`" + `status` + "`" + `,
    ` + "`" + `summary` + "`" + `,
    ` + "`" + `tekton_ref` + "`" + `,
    ` + "`" + `created_at` + "`" + `,
    ` + "`" + `started_at` + "`" + `,
    ` + "`" + `finished_at` + "`" + `
FROM ` + "`" + `DEPLOYMENTS` + "`" + `
WHERE ` + "`" + `project_id` + "`" + ` = ?
ORDER BY ` + "`" + `created_at` + "`" + ` DESC
LIMIT ? OFFSET ?
`

type FindDeploymentsByProjectIDParams struct {
	ProjectID uint32 `json:"project_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) FindDeploymentsByProjectID(ctx context.Context, arg FindDeploymentsByProjectIDParams) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, findDeploymentsByProjectID, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.DeploymentID,
			&i.ProjectID,
			&i.Status,
			&i.Summary,
			&i.TektonRef,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findLatestDeploymentByProjectID = `-- name: FindLatestDeploymentByProjectID :one
SELECT
    ` + "`" + `deployment_id` + "`" + `,
    ` + "`" + `project_id` + "`" + `,
    ` + "`" + `status` + "`" + `,
    ` + "`" + `summary` + "`" + `,
    ` + "`" + `tekton_ref` + "`" + `,
    ` + "`" + `created_at` + "`" + `,
    ` + "`" + `started_at` + "`" + `,
    ` + "`" + `finished_at` + "`" + `
FROM ` + "`" + `DEPLOYMENTS` + "`" + `
WHERE ` + "`" + `project_id` + "`" + ` = ?
ORDER BY ` + "`" + `created_at` + "`" + ` DESC
LIMIT 1
`

func (q *Queries) FindLatestDeploymentByProjectID(ctx context.Context, projectID uint32) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, findLatestDeploymentByProjectID, projectID)
	var i Deployment
	err := row.Scan(
		&i.DeploymentID,
		&i.ProjectID,
		&i.Status,
		&i.Summary,
		&i.TektonRef,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const updateDeployment = `-- name: UpdateDeployment :exec
UPDATE ` + "`" + `DEPLOYMENTS` + "`" + `
SET
    ` + "`" + `status` + "`" + ` = ?,
    ` + "`" + `summary` + "`" + ` = ?,
    ` + "`" + `tekton_ref` + "`" + ` = ?,
    ` + "`" + `started_at` + "`" + ` = ?,
    ` + "`" + `finished_at` + "`" + ` = ?
WHERE
    ` + "`" + `deployment_id` + "`" + ` = ?
`

type UpdateDeploymentParams struct {
	Status       DeploymentsStatus `json:"status"`
	Summary      sql.NullString    `json:"summary"`
	TektonRef    sql.NullString    `json:"tekton_ref"`
	StartedAt    sql.NullTime      `json:"started_at"`
	FinishedAt   sql.NullTime      `json:"finished_at"`
	DeploymentID uint32            `json:"deployment_id"`
}

func (q *Queries) UpdateDeployment(ctx context.Context, arg UpdateDeploymentParams) error {
	_, err := q.db.ExecContext(ctx, updateDeployment,
		arg.Status,
		arg.Summary,
		arg.TektonRef,
		arg.StartedAt,
		arg.FinishedAt,
		arg.DeploymentID,
	)
	return err
}
