// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_locks.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const getDeploymentLock = `-- name: GetDeploymentLock :one

SELECT
    project_id, token, expires_at
FROM DEPLOYMENT_LOCKS
WHERE project_id = ?
`

// Deployment Locks CRUD
func (q *Queries) GetDeploymentLock(ctx context.Context, projectID uint32) (DeploymentLock, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentLock, projectID)
	var i DeploymentLock
	err := row.Scan(&i.ProjectID, &i.Token, &i.ExpiresAt)
	return i, err
}

const insertNewLock = `-- name: InsertNewLock :execresult
INSERT INTO DEPLOYMENT_LOCKS (
    project_id, token, expires_at
) VALUES (?, ?, ?)
`

type InsertNewLockParams struct {
	ProjectID uint32    `json:"project_id"`
	Token     uint64    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) InsertNewLock(ctx context.Context, arg InsertNewLockParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertNewLock, arg.ProjectID, arg.Token, arg.ExpiresAt)
}

const releaseDeploymentLock = `-- name: ReleaseDeploymentLock :execresult
UPDATE DEPLOYMENT_LOCKS SET
    expires_at = NOW()
WHERE project_id = ? AND token <= ?
`

type ReleaseDeploymentLockParams struct {
	ProjectID uint32 `json:"project_id"`
	Token     uint64 `json:"token"`
}

func (q *Queries) ReleaseDeploymentLock(ctx context.Context, arg ReleaseDeploymentLockParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, releaseDeploymentLock, arg.ProjectID, arg.Token)
}

const renewDeploymentLock = `-- name: RenewDeploymentLock :execresult
UPDATE DEPLOYMENT_LOCKS SET
    expires_at = ?
WHERE project_id = ? AND token <= ? AND expires_at > NOW()
`

type RenewDeploymentLockParams struct {
	ExpiresAt time.Time `json:"expires_at"`
	ProjectID uint32    `json:"project_id"`
	Token     uint64    `json:"token"`
}

func (q *Queries) RenewDeploymentLock(ctx context.Context, arg RenewDeploymentLockParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, renewDeploymentLock, arg.ExpiresAt, arg.ProjectID, arg.Token)
}

const updateExpiredLock = `-- name: UpdateExpiredLock :execresult
UPDATE DEPLOYMENT_LOCKS SET
    token = token + 1,
    expires_at = ?
WHERE project_id = ? AND expires_at <= NOW()
`

type UpdateExpiredLockParams struct {
	ExpiresAt time.Time `json:"expires_at"`
	ProjectID uint32    `json:"project_id"`
}

func (q *Queries) UpdateExpiredLock(ctx context.Context, arg UpdateExpiredLockParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateExpiredLock, arg.ExpiresAt, arg.ProjectID)
}
