// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_summary.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"
)

const getProjectsSummary = `-- name: GetProjectsSummary :many

SELECT
    p.project_id,
    COUNT(DISTINCT c.container_id) as container_count,
    COUNT(DISTINCT CASE WHEN n.fqdn IS NOT NULL AND n.fqdn != '' THEN n.network_id END) as domain_count,
    GROUP_CONCAT(DISTINCT CASE WHEN n.fqdn IS NOT NULL AND n.fqdn != '' THEN n.fqdn END ORDER BY n.fqdn SEPARATOR ',') as domains
FROM PROJECTS p
LEFT JOIN CONTAINERS c ON p.project_id = c.project_id AND c.is_deleted = FALSE
LEFT JOIN NETWORKS n ON c.container_id = n.container_id
WHERE p.project_id IN (/*SLICE:project_ids*/?)
AND p.is_deleted = FALSE
GROUP BY p.project_id
ORDER BY p.project_id
`

type GetProjectsSummaryRow struct {
	ProjectID      uint32         `json:"project_id"`
	ContainerCount int64          `json:"container_count"`
	DomainCount    int64          `json:"domain_count"`
	Domains        sql.NullString `json:"domains"`
}

// Project Summary Queries
// These queries aggregate container and domain information for project list view
func (q *Queries) GetProjectsSummary(ctx context.Context, projectIds []uint32) ([]GetProjectsSummaryRow, error) {
	query := getProjectsSummary
	var queryParams []interface{}
	if len(projectIds) > 0 {
		for _, v := range projectIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:project_ids*/?", strings.Repeat(",?", len(projectIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:project_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProjectsSummaryRow{}
	for rows.Next() {
		var i GetProjectsSummaryRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.ContainerCount,
			&i.DomainCount,
			&i.Domains,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
