// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountProjects(ctx context.Context) (int64, error)
	CountVolumes(ctx context.Context) (int64, error)
	CountVolumesByProjectID(ctx context.Context, projectID uint32) (int64, error)
	CreateBuildHistory(ctx context.Context, arg CreateBuildHistoryParams) (sql.Result, error)
	CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (sql.Result, error)
	// Projects CRUD
	CreateProject(ctx context.Context, arg CreateProjectParams) (sql.Result, error)
	// ProjectUsers CRUD
	CreateProjectUser(ctx context.Context, arg CreateProjectUserParams) (sql.Result, error)
	// Volumes CRUD (Independent Aggregate Root)
	CreateVolume(ctx context.Context, arg CreateVolumeParams) (sql.Result, error)
	DeleteProject(ctx context.Context, arg DeleteProjectParams) (sql.Result, error)
	DeleteProjectUser(ctx context.Context, arg DeleteProjectUserParams) (sql.Result, error)
	DeleteProjectUsersByProjectID(ctx context.Context, arg DeleteProjectUsersByProjectIDParams) (sql.Result, error)
	DeleteVolume(ctx context.Context, volumeID uint32) (sql.Result, error)
	DeleteVolumesByProjectID(ctx context.Context, projectID uint32) (sql.Result, error)
	ExistsByNameAndUserID(ctx context.Context, arg ExistsByNameAndUserIDParams) (bool, error)
	ExistsBySlug(ctx context.Context, slug string) (bool, error)
	ExistsVolumeByName(ctx context.Context, arg ExistsVolumeByNameParams) (bool, error)
	ExistsVolumeBySlug(ctx context.Context, slug sql.NullString) (bool, error)
	// Returns all non-completed build histories for a container.
	// Includes: untracked, running, backend_tracking_lost (recoverable states)
	// Excludes: success, failed, cancelled, skipped, backend_trigger_failed, backend_tracking_failed (terminal states)
	FindActiveBuildHistoriesByContainerID(ctx context.Context, containerID uint32) ([]BuildHistory, error)
	// Returns all non-completed deployments for a project.
	// Includes: untracked, running, backend_tracking_lost (recoverable states)
	// Excludes: success, failed, cancelled, backend_trigger_failed, backend_tracking_failed (terminal states)
	FindActiveDeploymentsByProjectID(ctx context.Context, projectID uint32) ([]Deployment, error)
	FindBuildHistoriesByContainerID(ctx context.Context, arg FindBuildHistoriesByContainerIDParams) ([]BuildHistory, error)
	FindBuildHistoryByID(ctx context.Context, buildHistoryID uint32) (BuildHistory, error)
	FindBuildHistoryByTektonPipelineRunName(ctx context.Context, tektonPipelineRunName sql.NullString) (BuildHistory, error)
	FindDeploymentByID(ctx context.Context, deploymentID uint32) (Deployment, error)
	FindDeploymentByTektonPipelineRunName(ctx context.Context, tektonPipelineRunName sql.NullString) (Deployment, error)
	FindDeploymentsByProjectID(ctx context.Context, arg FindDeploymentsByProjectIDParams) ([]Deployment, error)
	FindLatestBuildHistoryByContainerID(ctx context.Context, containerID uint32) (BuildHistory, error)
	FindLatestDeploymentByProjectID(ctx context.Context, projectID uint32) (Deployment, error)
	FindProjectsWithActiveOperations(ctx context.Context) ([]FindProjectsWithActiveOperationsRow, error)
	GetAllProjectUsersByProjectID(ctx context.Context, projectID uint32) ([]ProjectUser, error)
	GetProjectByID(ctx context.Context, projectID uint32) (GetProjectByIDRow, error)
	GetProjectByIDForUpdate(ctx context.Context, projectID uint32) (GetProjectByIDForUpdateRow, error)
	GetProjectBySlug(ctx context.Context, slug string) (GetProjectBySlugRow, error)
	GetProjectUserRole(ctx context.Context, arg GetProjectUserRoleParams) (ProjectUserRole, error)
	GetProjectUsersByProjectID(ctx context.Context, projectID uint32) ([]ProjectUser, error)
	GetProjectUsersByProjectIDs(ctx context.Context, projectIds []uint32) ([]ProjectUser, error)
	// Project Summary Queries
	// These queries aggregate container and domain information for project list view
	GetProjectsSummary(ctx context.Context, projectIds []uint32) ([]GetProjectsSummaryRow, error)
	GetTotalCapacityByProjectID(ctx context.Context, projectID uint32) (interface{}, error)
	GetVolumeByID(ctx context.Context, volumeID uint32) (Volume, error)
	GetVolumeByName(ctx context.Context, arg GetVolumeByNameParams) (Volume, error)
	GetVolumeBySlug(ctx context.Context, slug sql.NullString) (Volume, error)
	GetVolumesByProjectID(ctx context.Context, projectID uint32) ([]Volume, error)
	HardDeleteProjectUsersByProjectID(ctx context.Context, projectID uint32) (sql.Result, error)
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]ListProjectsRow, error)
	ListProjectsByUserID(ctx context.Context, userID uint32) ([]ListProjectsByUserIDRow, error)
	ListVolumes(ctx context.Context, arg ListVolumesParams) ([]Volume, error)
	RestoreProjectUser(ctx context.Context, arg RestoreProjectUserParams) (sql.Result, error)
	UpdateBuildHistory(ctx context.Context, arg UpdateBuildHistoryParams) (sql.Result, error)
	UpdateDeployment(ctx context.Context, arg UpdateDeploymentParams) (sql.Result, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (sql.Result, error)
	UpdateProjectUser(ctx context.Context, arg UpdateProjectUserParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
