// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: volumes.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countVolumes = `-- name: CountVolumes :one
SELECT COUNT(*) as total FROM VOLUMES
`

func (q *Queries) CountVolumes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVolumes)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countVolumesByProjectID = `-- name: CountVolumesByProjectID :one
SELECT COUNT(*) as total FROM VOLUMES WHERE project_id = ?
`

func (q *Queries) CountVolumesByProjectID(ctx context.Context, projectID uint32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVolumesByProjectID, projectID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createVolume = `-- name: CreateVolume :execresult

INSERT INTO VOLUMES (
    project_id, name, slug, capacity,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?, NULL)
`

type CreateVolumeParams struct {
	ProjectID uint32         `json:"project_id"`
	Name      string         `json:"name"`
	Slug      sql.NullString `json:"slug"`
	Capacity  uint32         `json:"capacity"`
	CreatedAt time.Time      `json:"created_at"`
}

// Volumes CRUD (Independent Aggregate Root)
func (q *Queries) CreateVolume(ctx context.Context, arg CreateVolumeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createVolume,
		arg.ProjectID,
		arg.Name,
		arg.Slug,
		arg.Capacity,
		arg.CreatedAt,
	)
}

const deleteVolume = `-- name: DeleteVolume :execresult
DELETE FROM VOLUMES WHERE volume_id = ?
`

func (q *Queries) DeleteVolume(ctx context.Context, volumeID uint32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteVolume, volumeID)
}

const deleteVolumesByProjectID = `-- name: DeleteVolumesByProjectID :execresult
DELETE FROM VOLUMES WHERE project_id = ?
`

func (q *Queries) DeleteVolumesByProjectID(ctx context.Context, projectID uint32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteVolumesByProjectID, projectID)
}

const existsVolumeByName = `-- name: ExistsVolumeByName :one
SELECT EXISTS(
    SELECT 1 FROM VOLUMES
    WHERE project_id = ? AND name = ?
) as volume_exists
`

type ExistsVolumeByNameParams struct {
	ProjectID uint32 `json:"project_id"`
	Name      string `json:"name"`
}

func (q *Queries) ExistsVolumeByName(ctx context.Context, arg ExistsVolumeByNameParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsVolumeByName, arg.ProjectID, arg.Name)
	var volume_exists bool
	err := row.Scan(&volume_exists)
	return volume_exists, err
}

const existsVolumeBySlug = `-- name: ExistsVolumeBySlug :one
SELECT EXISTS(
    SELECT 1 FROM VOLUMES
    WHERE slug = ?
) as volume_exists
`

func (q *Queries) ExistsVolumeBySlug(ctx context.Context, slug sql.NullString) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsVolumeBySlug, slug)
	var volume_exists bool
	err := row.Scan(&volume_exists)
	return volume_exists, err
}

const getTotalCapacityByProjectID = `-- name: GetTotalCapacityByProjectID :one
SELECT COALESCE(SUM(capacity), 0) as total_capacity
FROM VOLUMES
WHERE project_id = ?
`

func (q *Queries) GetTotalCapacityByProjectID(ctx context.Context, projectID uint32) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getTotalCapacityByProjectID, projectID)
	var total_capacity interface{}
	err := row.Scan(&total_capacity)
	return total_capacity, err
}

const getVolumeByID = `-- name: GetVolumeByID :one
SELECT
    volume_id, project_id, name, slug, capacity,
    created_at, updated_at
FROM VOLUMES
WHERE volume_id = ?
`

func (q *Queries) GetVolumeByID(ctx context.Context, volumeID uint32) (Volume, error) {
	row := q.db.QueryRowContext(ctx, getVolumeByID, volumeID)
	var i Volume
	err := row.Scan(
		&i.VolumeID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVolumeByName = `-- name: GetVolumeByName :one
SELECT
    volume_id, project_id, name, slug, capacity,
    created_at, updated_at
FROM VOLUMES
WHERE project_id = ? AND name = ?
`

type GetVolumeByNameParams struct {
	ProjectID uint32 `json:"project_id"`
	Name      string `json:"name"`
}

func (q *Queries) GetVolumeByName(ctx context.Context, arg GetVolumeByNameParams) (Volume, error) {
	row := q.db.QueryRowContext(ctx, getVolumeByName, arg.ProjectID, arg.Name)
	var i Volume
	err := row.Scan(
		&i.VolumeID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVolumeBySlug = `-- name: GetVolumeBySlug :one
SELECT
    volume_id, project_id, name, slug, capacity,
    created_at, updated_at
FROM VOLUMES
WHERE slug = ?
`

func (q *Queries) GetVolumeBySlug(ctx context.Context, slug sql.NullString) (Volume, error) {
	row := q.db.QueryRowContext(ctx, getVolumeBySlug, slug)
	var i Volume
	err := row.Scan(
		&i.VolumeID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVolumesByProjectID = `-- name: GetVolumesByProjectID :many
SELECT
    volume_id, project_id, name, slug, capacity,
    created_at, updated_at
FROM VOLUMES
WHERE project_id = ?
ORDER BY created_at ASC
`

func (q *Queries) GetVolumesByProjectID(ctx context.Context, projectID uint32) ([]Volume, error) {
	rows, err := q.db.QueryContext(ctx, getVolumesByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Volume{}
	for rows.Next() {
		var i Volume
		if err := rows.Scan(
			&i.VolumeID,
			&i.ProjectID,
			&i.Name,
			&i.Slug,
			&i.Capacity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVolumes = `-- name: ListVolumes :many
SELECT
    volume_id, project_id, name, slug, capacity,
    created_at, updated_at
FROM VOLUMES
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListVolumesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListVolumes(ctx context.Context, arg ListVolumesParams) ([]Volume, error) {
	rows, err := q.db.QueryContext(ctx, listVolumes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Volume{}
	for rows.Next() {
		var i Volume
		if err := rows.Scan(
			&i.VolumeID,
			&i.ProjectID,
			&i.Name,
			&i.Slug,
			&i.Capacity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
