// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countProjects = `-- name: CountProjects :one
SELECT COUNT(*) as total FROM PROJECTS WHERE is_deleted = FALSE
`

func (q *Queries) CountProjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjects)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createProject = `-- name: CreateProject :execresult

INSERT INTO PROJECTS (
    name, slug, fqdn, status, plan,
    cpu_limit, memory_limit, disk_limit, traffic_limit,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateProjectParams struct {
	Name         string         `json:"name"`
	Slug         string         `json:"slug"`
	Fqdn         sql.NullString `json:"fqdn"`
	Status       ProjectsStatus `json:"status"`
	Plan         sql.NullString `json:"plan"`
	CpuLimit     sql.NullInt32  `json:"cpu_limit"`
	MemoryLimit  sql.NullInt32  `json:"memory_limit"`
	DiskLimit    sql.NullInt32  `json:"disk_limit"`
	TrafficLimit sql.NullInt64  `json:"traffic_limit"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

// Projects CRUD
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createProject,
		arg.Name,
		arg.Slug,
		arg.Fqdn,
		arg.Status,
		arg.Plan,
		arg.CpuLimit,
		arg.MemoryLimit,
		arg.DiskLimit,
		arg.TrafficLimit,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const createProjectUser = `-- name: CreateProjectUser :execresult

INSERT INTO PROJECT_USER (
    project_id, user_id, role,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?)
`

type CreateProjectUserParams struct {
	ProjectID uint32          `json:"project_id"`
	UserID    uint32          `json:"user_id"`
	Role      ProjectUserRole `json:"role"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt sql.NullTime    `json:"updated_at"`
}

// ProjectUsers CRUD
func (q *Queries) CreateProjectUser(ctx context.Context, arg CreateProjectUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createProjectUser,
		arg.ProjectID,
		arg.UserID,
		arg.Role,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const deleteProject = `-- name: DeleteProject :execresult
UPDATE PROJECTS SET
    is_deleted = TRUE,
    deleted_at = ?,
    updated_at = ?
WHERE project_id = ?
`

type DeleteProjectParams struct {
	DeletedAt sql.NullTime `json:"deleted_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	ProjectID uint32       `json:"project_id"`
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteProject, arg.DeletedAt, arg.UpdatedAt, arg.ProjectID)
}

const deleteProjectUser = `-- name: DeleteProjectUser :execresult
UPDATE PROJECT_USER SET
    is_deleted = TRUE,
    deleted_at = ?,
    updated_at = ?
WHERE project_id = ? AND user_id = ?
`

type DeleteProjectUserParams struct {
	DeletedAt sql.NullTime `json:"deleted_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	ProjectID uint32       `json:"project_id"`
	UserID    uint32       `json:"user_id"`
}

func (q *Queries) DeleteProjectUser(ctx context.Context, arg DeleteProjectUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteProjectUser,
		arg.DeletedAt,
		arg.UpdatedAt,
		arg.ProjectID,
		arg.UserID,
	)
}

const deleteProjectUsersByProjectID = `-- name: DeleteProjectUsersByProjectID :execresult
UPDATE PROJECT_USER SET
    is_deleted = TRUE,
    deleted_at = ?,
    updated_at = ?
WHERE project_id = ?
`

type DeleteProjectUsersByProjectIDParams struct {
	DeletedAt sql.NullTime `json:"deleted_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	ProjectID uint32       `json:"project_id"`
}

func (q *Queries) DeleteProjectUsersByProjectID(ctx context.Context, arg DeleteProjectUsersByProjectIDParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteProjectUsersByProjectID, arg.DeletedAt, arg.UpdatedAt, arg.ProjectID)
}

const existsBySlug = `-- name: ExistsBySlug :one
SELECT EXISTS(SELECT 1 FROM PROJECTS WHERE slug = ? AND is_deleted = FALSE) as project_exists
`

func (q *Queries) ExistsBySlug(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsBySlug, slug)
	var project_exists bool
	err := row.Scan(&project_exists)
	return project_exists, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT
    project_id, name, slug, fqdn, status, plan,
    cpu_limit, memory_limit, disk_limit, traffic_limit,
    created_at, updated_at, deleted_at, is_deleted
FROM PROJECTS
WHERE project_id = ? AND is_deleted = FALSE
`

func (q *Queries) GetProjectByID(ctx context.Context, projectID uint32) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByID, projectID)
	var i Project
	err := row.Scan(
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.Fqdn,
		&i.Status,
		&i.Plan,
		&i.CpuLimit,
		&i.MemoryLimit,
		&i.DiskLimit,
		&i.TrafficLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT
    project_id, name, slug, fqdn, status, plan,
    cpu_limit, memory_limit, disk_limit, traffic_limit,
    created_at, updated_at, deleted_at, is_deleted
FROM PROJECTS
WHERE slug = ? AND is_deleted = FALSE
`

func (q *Queries) GetProjectBySlug(ctx context.Context, slug string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectBySlug, slug)
	var i Project
	err := row.Scan(
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.Fqdn,
		&i.Status,
		&i.Plan,
		&i.CpuLimit,
		&i.MemoryLimit,
		&i.DiskLimit,
		&i.TrafficLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getProjectUserRole = `-- name: GetProjectUserRole :one
SELECT role
FROM PROJECT_USER
WHERE project_id = ? AND user_id = ? AND is_deleted = FALSE
`

type GetProjectUserRoleParams struct {
	ProjectID uint32 `json:"project_id"`
	UserID    uint32 `json:"user_id"`
}

func (q *Queries) GetProjectUserRole(ctx context.Context, arg GetProjectUserRoleParams) (ProjectUserRole, error) {
	row := q.db.QueryRowContext(ctx, getProjectUserRole, arg.ProjectID, arg.UserID)
	var role ProjectUserRole
	err := row.Scan(&role)
	return role, err
}

const getProjectUsersByProjectID = `-- name: GetProjectUsersByProjectID :many
SELECT
    project_user_id, project_id, user_id, role,
    created_at, updated_at, deleted_at, is_deleted
FROM PROJECT_USER
WHERE project_id = ? AND is_deleted = FALSE
ORDER BY created_at ASC
`

func (q *Queries) GetProjectUsersByProjectID(ctx context.Context, projectID uint32) ([]ProjectUser, error) {
	rows, err := q.db.QueryContext(ctx, getProjectUsersByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectUser{}
	for rows.Next() {
		var i ProjectUser
		if err := rows.Scan(
			&i.ProjectUserID,
			&i.ProjectID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hardDeleteProjectUsersByProjectID = `-- name: HardDeleteProjectUsersByProjectID :execresult
DELETE FROM PROJECT_USER
WHERE project_id = ?
`

func (q *Queries) HardDeleteProjectUsersByProjectID(ctx context.Context, projectID uint32) (sql.Result, error) {
	return q.db.ExecContext(ctx, hardDeleteProjectUsersByProjectID, projectID)
}

const listProjects = `-- name: ListProjects :many
SELECT
    project_id, name, slug, fqdn, status, plan,
    cpu_limit, memory_limit, disk_limit, traffic_limit,
    created_at, updated_at, deleted_at, is_deleted
FROM PROJECTS
WHERE is_deleted = FALSE
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListProjectsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ProjectID,
			&i.Name,
			&i.Slug,
			&i.Fqdn,
			&i.Status,
			&i.Plan,
			&i.CpuLimit,
			&i.MemoryLimit,
			&i.DiskLimit,
			&i.TrafficLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByUserID = `-- name: ListProjectsByUserID :many
SELECT DISTINCT
    p.project_id, p.name, p.slug, p.fqdn, p.status, p.plan,
    p.cpu_limit, p.memory_limit, p.disk_limit, p.traffic_limit,
    p.created_at, p.updated_at, p.deleted_at, p.is_deleted
FROM PROJECTS p
JOIN PROJECT_USER pu ON p.project_id = pu.project_id
WHERE pu.user_id = ?
AND p.is_deleted = FALSE
AND pu.is_deleted = FALSE
ORDER BY p.created_at DESC
`

func (q *Queries) ListProjectsByUserID(ctx context.Context, userID uint32) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ProjectID,
			&i.Name,
			&i.Slug,
			&i.Fqdn,
			&i.Status,
			&i.Plan,
			&i.CpuLimit,
			&i.MemoryLimit,
			&i.DiskLimit,
			&i.TrafficLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :execresult
UPDATE PROJECTS SET
    name = ?, fqdn = ?, status = ?, plan = ?,
    cpu_limit = ?, memory_limit = ?, disk_limit = ?, traffic_limit = ?,
    updated_at = ?
WHERE project_id = ? AND is_deleted = FALSE
`

type UpdateProjectParams struct {
	Name         string         `json:"name"`
	Fqdn         sql.NullString `json:"fqdn"`
	Status       ProjectsStatus `json:"status"`
	Plan         sql.NullString `json:"plan"`
	CpuLimit     sql.NullInt32  `json:"cpu_limit"`
	MemoryLimit  sql.NullInt32  `json:"memory_limit"`
	DiskLimit    sql.NullInt32  `json:"disk_limit"`
	TrafficLimit sql.NullInt64  `json:"traffic_limit"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
	ProjectID    uint32         `json:"project_id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateProject,
		arg.Name,
		arg.Fqdn,
		arg.Status,
		arg.Plan,
		arg.CpuLimit,
		arg.MemoryLimit,
		arg.DiskLimit,
		arg.TrafficLimit,
		arg.UpdatedAt,
		arg.ProjectID,
	)
}

const updateProjectUser = `-- name: UpdateProjectUser :execresult
UPDATE PROJECT_USER SET
    role = ?, updated_at = ?
WHERE project_id = ? AND user_id = ? AND is_deleted = FALSE
`

type UpdateProjectUserParams struct {
	Role      ProjectUserRole `json:"role"`
	UpdatedAt sql.NullTime    `json:"updated_at"`
	ProjectID uint32          `json:"project_id"`
	UserID    uint32          `json:"user_id"`
}

func (q *Queries) UpdateProjectUser(ctx context.Context, arg UpdateProjectUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateProjectUser,
		arg.Role,
		arg.UpdatedAt,
		arg.ProjectID,
		arg.UserID,
	)
}
