// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountProjects(ctx context.Context) (int64, error)
	CountVolumes(ctx context.Context) (int64, error)
	CountVolumesByProjectID(ctx context.Context, projectID uint32) (int64, error)
	// Projects CRUD
	CreateProject(ctx context.Context, arg CreateProjectParams) (sql.Result, error)
	// ProjectUsers CRUD
	CreateProjectUser(ctx context.Context, arg CreateProjectUserParams) (sql.Result, error)
	// Volumes CRUD (Independent Aggregate Root)
	CreateVolume(ctx context.Context, arg CreateVolumeParams) (sql.Result, error)
	DeleteProject(ctx context.Context, arg DeleteProjectParams) (sql.Result, error)
	DeleteProjectUser(ctx context.Context, arg DeleteProjectUserParams) (sql.Result, error)
	DeleteProjectUsersByProjectID(ctx context.Context, arg DeleteProjectUsersByProjectIDParams) (sql.Result, error)
	DeleteVolume(ctx context.Context, volumeID uint32) (sql.Result, error)
	DeleteVolumesByProjectID(ctx context.Context, projectID uint32) (sql.Result, error)
	ExistsByNameAndUserID(ctx context.Context, arg ExistsByNameAndUserIDParams) (bool, error)
	ExistsBySlug(ctx context.Context, slug string) (bool, error)
	ExistsVolumeByName(ctx context.Context, arg ExistsVolumeByNameParams) (bool, error)
	GetAllProjectUsersByProjectID(ctx context.Context, projectID uint32) ([]ProjectUser, error)
	GetProjectByID(ctx context.Context, projectID uint32) (Project, error)
	GetProjectByIDForUpdate(ctx context.Context, projectID uint32) (Project, error)
	GetProjectBySlug(ctx context.Context, slug string) (Project, error)
	GetProjectUserRole(ctx context.Context, arg GetProjectUserRoleParams) (ProjectUserRole, error)
	GetProjectUsersByProjectID(ctx context.Context, projectID uint32) ([]ProjectUser, error)
	GetProjectUsersByProjectIDs(ctx context.Context, projectIds []uint32) ([]ProjectUser, error)
	GetTotalCapacityByProjectID(ctx context.Context, projectID uint32) (interface{}, error)
	GetVolumeByID(ctx context.Context, volumeID uint32) (Volume, error)
	GetVolumeByName(ctx context.Context, arg GetVolumeByNameParams) (Volume, error)
	GetVolumesByProjectID(ctx context.Context, projectID uint32) ([]Volume, error)
	HardDeleteProjectUsersByProjectID(ctx context.Context, projectID uint32) (sql.Result, error)
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error)
	ListProjectsByUserID(ctx context.Context, userID uint32) ([]Project, error)
	ListVolumes(ctx context.Context, arg ListVolumesParams) ([]Volume, error)
	RestoreProjectUser(ctx context.Context, arg RestoreProjectUserParams) (sql.Result, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (sql.Result, error)
	UpdateProjectUser(ctx context.Context, arg UpdateProjectUserParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
