// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/swm-launchpad/web-console-backend/internal/common/auth/jwt"
	"github.com/swm-launchpad/web-console-backend/internal/common/auth/password"
	"github.com/swm-launchpad/web-console-backend/internal/common/config"
	"github.com/swm-launchpad/web-console-backend/internal/common/db"
	"github.com/swm-launchpad/web-console-backend/internal/common/middleware"
	"github.com/swm-launchpad/web-console-backend/internal/user/application"
	"github.com/swm-launchpad/web-console-backend/internal/user/handler"
	"github.com/swm-launchpad/web-console-backend/internal/user/infrastructure"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	db, err := provideDatabase(configConfig)
	if err != nil {
		return nil, err
	}
	userRepository := infrastructure.NewUserRepository(db)
	jwtUtil := provideJWTUtil(configConfig)
	passwordUtil := password.NewPasswordUtil()
	registerUserUseCase := application.NewRegisterUserUseCase(userRepository, jwtUtil, passwordUtil)
	loginUserUseCase := application.NewLoginUserUseCase(userRepository, jwtUtil, passwordUtil)
	authHandler := handler.NewAuthHandler(registerUserUseCase, loginUserUseCase)
	getUserUseCase := application.NewGetUserUseCase(userRepository)
	userHandler := handler.NewUserHandler(getUserUseCase)
	authMiddleware := middleware.NewAuthMiddleware(jwtUtil)
	router := NewRouter(configConfig, db, authHandler, userHandler, authMiddleware)
	app := NewApp(configConfig, db, router)
	return app, nil
}

// wire.go:

func provideDatabase(cfg *config.Config) (*sql.DB, error) {
	return db.NewConnection(&cfg.Database)
}

func provideJWTUtil(cfg *config.Config) *jwt.JWTUtil {
	return jwt.NewJWTUtil(cfg.JWT.Secret)
}
