// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/swm-launchpad/web-console-backend/internal/common/auth/jwt"
	"github.com/swm-launchpad/web-console-backend/internal/common/auth/password"
	"github.com/swm-launchpad/web-console-backend/internal/common/config"
	"github.com/swm-launchpad/web-console-backend/internal/common/db"
	"github.com/swm-launchpad/web-console-backend/internal/common/email"
	"github.com/swm-launchpad/web-console-backend/internal/common/middleware"
	application2 "github.com/swm-launchpad/web-console-backend/internal/project/application"
	service2 "github.com/swm-launchpad/web-console-backend/internal/project/domain/service"
	handler2 "github.com/swm-launchpad/web-console-backend/internal/project/handler"
	"github.com/swm-launchpad/web-console-backend/internal/project/infrastructure/repository"
	"github.com/swm-launchpad/web-console-backend/internal/user/application"
	"github.com/swm-launchpad/web-console-backend/internal/user/domain/service"
	"github.com/swm-launchpad/web-console-backend/internal/user/handler"
	"github.com/swm-launchpad/web-console-backend/internal/user/infrastructure"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	db, err := provideDatabase(configConfig)
	if err != nil {
		return nil, err
	}
	userRepository := infrastructure.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	jwtUtil := provideJWTUtil(configConfig)
	passwordUtil := password.NewPasswordUtil()
	authService := service.NewAuthService(userService, jwtUtil, passwordUtil)
	tokenRepository := infrastructure.NewTokenRepository(db)
	tokenService := service.NewTokenService(tokenRepository)
	emailService := provideEmailService(configConfig)
	txManager := provideTxManager(db)
	registerUserUseCase := application.NewRegisterUserUseCase(authService, tokenService, emailService, txManager)
	loginUserUseCase := application.NewLoginUserUseCase(authService)
	authHandler := handler.NewAuthHandler(registerUserUseCase, loginUserUseCase)
	getUserUseCase := application.NewGetUserUseCase(userService)
	updateUserUseCase := application.NewUpdateUserUseCase(userService)
	changePasswordUseCase := application.NewChangePasswordUseCase(userService, authService)
	userHandler := handler.NewUserHandler(getUserUseCase, updateUserUseCase, changePasswordUseCase)
	verifyEmailUseCase := application.NewVerifyEmailUseCase(tokenService, userService, txManager)
	resendVerificationEmailUseCase := application.NewResendVerificationEmailUseCase(userService, tokenService, emailService, txManager)
	verificationHandler := handler.NewVerificationHandler(verifyEmailUseCase, resendVerificationEmailUseCase)
	requestPasswordResetUseCase := application.NewRequestPasswordResetUseCase(userService, tokenService, emailService, txManager)
	resetPasswordUseCase := application.NewResetPasswordUseCase(tokenService, authService, userService, txManager)
	passwordResetHandler := handler.NewPasswordResetHandler(requestPasswordResetUseCase, resetPasswordUseCase)
	projectRepository := repository.NewProjectRepository(db)
	slugService := service2.NewSlugService(projectRepository)
	projectService := service2.NewProjectService(projectRepository, slugService)
	createProjectUseCase := application2.NewCreateProjectUseCase(projectService, txManager)
	volumeRepository := repository.NewVolumeRepository(db)
	volumeService := service2.NewVolumeService(volumeRepository, projectRepository)
	getProjectUseCase := application2.NewGetProjectUseCase(projectService, volumeService)
	updateProjectUseCase := application2.NewUpdateProjectUseCase(projectService, txManager)
	deleteProjectUseCase := application2.NewDeleteProjectUseCase(projectService, volumeService, txManager)
	listProjectsUseCase := application2.NewListProjectsUseCase(projectService)
	permissionService := service2.NewPermissionService(projectRepository, volumeRepository)
	projectHandler := handler2.NewProjectHandler(createProjectUseCase, getProjectUseCase, updateProjectUseCase, deleteProjectUseCase, listProjectsUseCase, permissionService, projectService)
	addVolumeUseCase := application2.NewAddVolumeUseCase(volumeService, txManager)
	getVolumesUseCase := application2.NewGetVolumesUseCase(volumeService)
	removeVolumeUseCase := application2.NewRemoveVolumeUseCase(volumeService, txManager)
	volumeHandler := handler2.NewVolumeHandler(addVolumeUseCase, getVolumesUseCase, removeVolumeUseCase, permissionService)
	authMiddleware := middleware.NewAuthMiddleware(jwtUtil)
	router := NewRouter(configConfig, db, authHandler, userHandler, verificationHandler, passwordResetHandler, projectHandler, volumeHandler, authMiddleware)
	app := NewApp(configConfig, db, router)
	return app, nil
}

// wire.go:

// provideDatabase creates a database connection from config
func provideDatabase(cfg *config.Config) (*sql.DB, error) {
	return db.NewConnection(&cfg.Database)
}

// provideTxManager creates a transaction manager
func provideTxManager(database *sql.DB) db.TxManager {
	return db.NewTxManager(database)
}

// provideJWTUtil creates a JWT utility from config
func provideJWTUtil(cfg *config.Config) *jwt.JWTUtil {
	return jwt.NewJWTUtil(cfg.JWT.Secret)
}

// provideEmailService creates an email service from config
func provideEmailService(cfg *config.Config) email.Service {
	return email.NewService(
		cfg.Email.Host,
		cfg.Email.Port,
		cfg.Email.Username,
		cfg.Email.Password,
		cfg.Email.From,
		cfg.Frontend.URL,
	)
}
