// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: github_installations.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createGitHubInstallation = `-- name: CreateGitHubInstallation :execresult
INSERT INTO GITHUB_INSTALLATIONS (
    installation_id, user_id, account_login, account_type, status,
    cached_token, token_expires_at,
    is_deleted, deleted_at, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateGitHubInstallationParams struct {
	InstallationID uint64                         `json:"installation_id"`
	UserID         uint32                         `json:"user_id"`
	AccountLogin   string                         `json:"account_login"`
	AccountType    GithubInstallationsAccountType `json:"account_type"`
	Status         GithubInstallationsStatus      `json:"status"`
	CachedToken    sql.NullString                 `json:"cached_token"`
	TokenExpiresAt sql.NullTime                   `json:"token_expires_at"`
	IsDeleted      bool                           `json:"is_deleted"`
	DeletedAt      sql.NullTime                   `json:"deleted_at"`
	CreatedAt      time.Time                      `json:"created_at"`
	UpdatedAt      sql.NullTime                   `json:"updated_at"`
}

func (q *Queries) CreateGitHubInstallation(ctx context.Context, arg CreateGitHubInstallationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createGitHubInstallation,
		arg.InstallationID,
		arg.UserID,
		arg.AccountLogin,
		arg.AccountType,
		arg.Status,
		arg.CachedToken,
		arg.TokenExpiresAt,
		arg.IsDeleted,
		arg.DeletedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const deleteGitHubInstallation = `-- name: DeleteGitHubInstallation :execresult
UPDATE GITHUB_INSTALLATIONS SET
    is_deleted = TRUE,
    deleted_at = ?,
    updated_at = ?,
    cached_token = NULL,
    token_expires_at = NULL
WHERE installation_id = ?
`

type DeleteGitHubInstallationParams struct {
	DeletedAt      sql.NullTime `json:"deleted_at"`
	UpdatedAt      sql.NullTime `json:"updated_at"`
	InstallationID uint64       `json:"installation_id"`
}

func (q *Queries) DeleteGitHubInstallation(ctx context.Context, arg DeleteGitHubInstallationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteGitHubInstallation, arg.DeletedAt, arg.UpdatedAt, arg.InstallationID)
}

const existsByInstallationID = `-- name: ExistsByInstallationID :one
SELECT EXISTS(SELECT 1 FROM GITHUB_INSTALLATIONS WHERE installation_id = ? AND is_deleted = FALSE AND status = 'active') as installation_exists
`

func (q *Queries) ExistsByInstallationID(ctx context.Context, installationID uint64) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsByInstallationID, installationID)
	var installation_exists bool
	err := row.Scan(&installation_exists)
	return installation_exists, err
}

const findInstallationByIDIncludingRevoked = `-- name: FindInstallationByIDIncludingRevoked :one
SELECT
    installation_id, user_id, account_login, account_type, status,
    cached_token, token_expires_at,
    is_deleted, deleted_at, created_at, updated_at
FROM GITHUB_INSTALLATIONS
WHERE installation_id = ?
`

type FindInstallationByIDIncludingRevokedRow struct {
	InstallationID uint64                         `json:"installation_id"`
	UserID         uint32                         `json:"user_id"`
	AccountLogin   string                         `json:"account_login"`
	AccountType    GithubInstallationsAccountType `json:"account_type"`
	Status         GithubInstallationsStatus      `json:"status"`
	CachedToken    sql.NullString                 `json:"cached_token"`
	TokenExpiresAt sql.NullTime                   `json:"token_expires_at"`
	IsDeleted      bool                           `json:"is_deleted"`
	DeletedAt      sql.NullTime                   `json:"deleted_at"`
	CreatedAt      time.Time                      `json:"created_at"`
	UpdatedAt      sql.NullTime                   `json:"updated_at"`
}

func (q *Queries) FindInstallationByIDIncludingRevoked(ctx context.Context, installationID uint64) (FindInstallationByIDIncludingRevokedRow, error) {
	row := q.db.QueryRowContext(ctx, findInstallationByIDIncludingRevoked, installationID)
	var i FindInstallationByIDIncludingRevokedRow
	err := row.Scan(
		&i.InstallationID,
		&i.UserID,
		&i.AccountLogin,
		&i.AccountType,
		&i.Status,
		&i.CachedToken,
		&i.TokenExpiresAt,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGitHubInstallationByID = `-- name: GetGitHubInstallationByID :one
SELECT
    installation_id, user_id, account_login, account_type, status,
    cached_token, token_expires_at,
    is_deleted, deleted_at, created_at, updated_at
FROM GITHUB_INSTALLATIONS
WHERE installation_id = ? AND is_deleted = FALSE AND status = 'active'
`

type GetGitHubInstallationByIDRow struct {
	InstallationID uint64                         `json:"installation_id"`
	UserID         uint32                         `json:"user_id"`
	AccountLogin   string                         `json:"account_login"`
	AccountType    GithubInstallationsAccountType `json:"account_type"`
	Status         GithubInstallationsStatus      `json:"status"`
	CachedToken    sql.NullString                 `json:"cached_token"`
	TokenExpiresAt sql.NullTime                   `json:"token_expires_at"`
	IsDeleted      bool                           `json:"is_deleted"`
	DeletedAt      sql.NullTime                   `json:"deleted_at"`
	CreatedAt      time.Time                      `json:"created_at"`
	UpdatedAt      sql.NullTime                   `json:"updated_at"`
}

func (q *Queries) GetGitHubInstallationByID(ctx context.Context, installationID uint64) (GetGitHubInstallationByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getGitHubInstallationByID, installationID)
	var i GetGitHubInstallationByIDRow
	err := row.Scan(
		&i.InstallationID,
		&i.UserID,
		&i.AccountLogin,
		&i.AccountType,
		&i.Status,
		&i.CachedToken,
		&i.TokenExpiresAt,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGitHubInstallationsByUserID = `-- name: GetGitHubInstallationsByUserID :many
SELECT
    installation_id, user_id, account_login, account_type, status,
    cached_token, token_expires_at,
    is_deleted, deleted_at, created_at, updated_at
FROM GITHUB_INSTALLATIONS
WHERE user_id = ? AND is_deleted = FALSE AND status = 'active'
ORDER BY created_at DESC
`

type GetGitHubInstallationsByUserIDRow struct {
	InstallationID uint64                         `json:"installation_id"`
	UserID         uint32                         `json:"user_id"`
	AccountLogin   string                         `json:"account_login"`
	AccountType    GithubInstallationsAccountType `json:"account_type"`
	Status         GithubInstallationsStatus      `json:"status"`
	CachedToken    sql.NullString                 `json:"cached_token"`
	TokenExpiresAt sql.NullTime                   `json:"token_expires_at"`
	IsDeleted      bool                           `json:"is_deleted"`
	DeletedAt      sql.NullTime                   `json:"deleted_at"`
	CreatedAt      time.Time                      `json:"created_at"`
	UpdatedAt      sql.NullTime                   `json:"updated_at"`
}

func (q *Queries) GetGitHubInstallationsByUserID(ctx context.Context, userID uint32) ([]GetGitHubInstallationsByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getGitHubInstallationsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGitHubInstallationsByUserIDRow{}
	for rows.Next() {
		var i GetGitHubInstallationsByUserIDRow
		if err := rows.Scan(
			&i.InstallationID,
			&i.UserID,
			&i.AccountLogin,
			&i.AccountType,
			&i.Status,
			&i.CachedToken,
			&i.TokenExpiresAt,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInstallationAsRevoked = `-- name: MarkInstallationAsRevoked :execresult
UPDATE GITHUB_INSTALLATIONS SET
    status = 'revoked',
    cached_token = NULL,
    token_expires_at = NULL,
    updated_at = ?
WHERE installation_id = ?
`

type MarkInstallationAsRevokedParams struct {
	UpdatedAt      sql.NullTime `json:"updated_at"`
	InstallationID uint64       `json:"installation_id"`
}

func (q *Queries) MarkInstallationAsRevoked(ctx context.Context, arg MarkInstallationAsRevokedParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, markInstallationAsRevoked, arg.UpdatedAt, arg.InstallationID)
}

const reactivateInstallation = `-- name: ReactivateInstallation :execresult
UPDATE GITHUB_INSTALLATIONS SET
    status = 'active',
    account_login = ?,
    account_type = ?,
    is_deleted = FALSE,
    deleted_at = NULL,
    updated_at = ?
WHERE installation_id = ?
`

type ReactivateInstallationParams struct {
	AccountLogin   string                         `json:"account_login"`
	AccountType    GithubInstallationsAccountType `json:"account_type"`
	UpdatedAt      sql.NullTime                   `json:"updated_at"`
	InstallationID uint64                         `json:"installation_id"`
}

func (q *Queries) ReactivateInstallation(ctx context.Context, arg ReactivateInstallationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, reactivateInstallation,
		arg.AccountLogin,
		arg.AccountType,
		arg.UpdatedAt,
		arg.InstallationID,
	)
}

const updateGitHubInstallation = `-- name: UpdateGitHubInstallation :execresult
UPDATE GITHUB_INSTALLATIONS SET
    cached_token = ?,
    token_expires_at = ?,
    updated_at = ?
WHERE installation_id = ?
`

type UpdateGitHubInstallationParams struct {
	CachedToken    sql.NullString `json:"cached_token"`
	TokenExpiresAt sql.NullTime   `json:"token_expires_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
	InstallationID uint64         `json:"installation_id"`
}

func (q *Queries) UpdateGitHubInstallation(ctx context.Context, arg UpdateGitHubInstallationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateGitHubInstallation,
		arg.CachedToken,
		arg.TokenExpiresAt,
		arg.UpdatedAt,
		arg.InstallationID,
	)
}
