// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth_states.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createOAuthState = `-- name: CreateOAuthState :execresult
INSERT INTO OAUTH_STATES (
    state, user_id, installation_id, expires_at, created_at, consumed_at
) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateOAuthStateParams struct {
	State          string        `json:"state"`
	UserID         uint32        `json:"user_id"`
	InstallationID sql.NullInt64 `json:"installation_id"`
	ExpiresAt      time.Time     `json:"expires_at"`
	CreatedAt      time.Time     `json:"created_at"`
	ConsumedAt     sql.NullTime  `json:"consumed_at"`
}

func (q *Queries) CreateOAuthState(ctx context.Context, arg CreateOAuthStateParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOAuthState,
		arg.State,
		arg.UserID,
		arg.InstallationID,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.ConsumedAt,
	)
}

const deleteExpiredOAuthStates = `-- name: DeleteExpiredOAuthStates :execresult
DELETE FROM OAUTH_STATES
WHERE expires_at < NOW() OR consumed_at IS NOT NULL
`

func (q *Queries) DeleteExpiredOAuthStates(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteExpiredOAuthStates)
}

const getOAuthStateByState = `-- name: GetOAuthStateByState :one
SELECT
    state, user_id, installation_id, expires_at, created_at, consumed_at
FROM OAUTH_STATES
WHERE state = ? LIMIT 1
`

func (q *Queries) GetOAuthStateByState(ctx context.Context, state string) (OauthState, error) {
	row := q.db.QueryRowContext(ctx, getOAuthStateByState, state)
	var i OauthState
	err := row.Scan(
		&i.State,
		&i.UserID,
		&i.InstallationID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.ConsumedAt,
	)
	return i, err
}

const markOAuthStateAsConsumed = `-- name: MarkOAuthStateAsConsumed :execresult
UPDATE OAUTH_STATES SET
    consumed_at = ?,
    installation_id = ?
WHERE state = ? AND consumed_at IS NULL
`

type MarkOAuthStateAsConsumedParams struct {
	ConsumedAt     sql.NullTime  `json:"consumed_at"`
	InstallationID sql.NullInt64 `json:"installation_id"`
	State          string        `json:"state"`
}

func (q *Queries) MarkOAuthStateAsConsumed(ctx context.Context, arg MarkOAuthStateAsConsumedParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, markOAuthStateAsConsumed, arg.ConsumedAt, arg.InstallationID, arg.State)
}
