// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createVerificationToken = `-- name: CreateVerificationToken :exec
INSERT INTO verification_tokens (
    user_id,
    token,
    token_type,
    expires_at,
    created_at
) VALUES (
    ?, ?, ?, ?, ?
)
`

type CreateVerificationTokenParams struct {
	UserID    uint32                      `json:"user_id"`
	Token     string                      `json:"token"`
	TokenType VerificationTokensTokenType `json:"token_type"`
	ExpiresAt time.Time                   `json:"expires_at"`
	CreatedAt time.Time                   `json:"created_at"`
}

func (q *Queries) CreateVerificationToken(ctx context.Context, arg CreateVerificationTokenParams) error {
	_, err := q.db.ExecContext(ctx, createVerificationToken,
		arg.UserID,
		arg.Token,
		arg.TokenType,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredTokens = `-- name: DeleteExpiredTokens :exec
DELETE FROM verification_tokens
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredTokens)
	return err
}

const deleteUserTokensByType = `-- name: DeleteUserTokensByType :exec
DELETE FROM verification_tokens
WHERE user_id = ? AND token_type = ?
`

type DeleteUserTokensByTypeParams struct {
	UserID    uint32                      `json:"user_id"`
	TokenType VerificationTokensTokenType `json:"token_type"`
}

func (q *Queries) DeleteUserTokensByType(ctx context.Context, arg DeleteUserTokensByTypeParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserTokensByType, arg.UserID, arg.TokenType)
	return err
}

const findLatestTokenByUserAndType = `-- name: FindLatestTokenByUserAndType :one
SELECT
    token_id,
    user_id,
    token,
    token_type,
    expires_at,
    used_at,
    created_at
FROM verification_tokens
WHERE user_id = ? AND token_type = ?
ORDER BY created_at DESC
LIMIT 1
`

type FindLatestTokenByUserAndTypeParams struct {
	UserID    uint32                      `json:"user_id"`
	TokenType VerificationTokensTokenType `json:"token_type"`
}

func (q *Queries) FindLatestTokenByUserAndType(ctx context.Context, arg FindLatestTokenByUserAndTypeParams) (VerificationToken, error) {
	row := q.db.QueryRowContext(ctx, findLatestTokenByUserAndType, arg.UserID, arg.TokenType)
	var i VerificationToken
	err := row.Scan(
		&i.TokenID,
		&i.UserID,
		&i.Token,
		&i.TokenType,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const findTokenByToken = `-- name: FindTokenByToken :one
SELECT
    token_id,
    user_id,
    token,
    token_type,
    expires_at,
    used_at,
    created_at
FROM verification_tokens
WHERE token = ?
LIMIT 1
`

func (q *Queries) FindTokenByToken(ctx context.Context, token string) (VerificationToken, error) {
	row := q.db.QueryRowContext(ctx, findTokenByToken, token)
	var i VerificationToken
	err := row.Scan(
		&i.TokenID,
		&i.UserID,
		&i.Token,
		&i.TokenType,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markTokenAsUsed = `-- name: MarkTokenAsUsed :exec
UPDATE verification_tokens
SET used_at = ?
WHERE token_id = ?
`

type MarkTokenAsUsedParams struct {
	UsedAt  sql.NullTime `json:"used_at"`
	TokenID uint32       `json:"token_id"`
}

func (q *Queries) MarkTokenAsUsed(ctx context.Context, arg MarkTokenAsUsedParams) error {
	_, err := q.db.ExecContext(ctx, markTokenAsUsed, arg.UsedAt, arg.TokenID)
	return err
}
