// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createUser = `-- name: CreateUser :execresult
INSERT INTO USERS (
    username, password_hash, password_updated_at,
    name, email, phone, organization,
    status, is_deleted, deleted_at, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	Username          string         `json:"username"`
	PasswordHash      string         `json:"password_hash"`
	PasswordUpdatedAt sql.NullTime   `json:"password_updated_at"`
	Name              sql.NullString `json:"name"`
	Email             string         `json:"email"`
	Phone             sql.NullString `json:"phone"`
	Organization      sql.NullString `json:"organization"`
	Status            UsersStatus    `json:"status"`
	IsDeleted         bool           `json:"is_deleted"`
	DeletedAt         sql.NullTime   `json:"deleted_at"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.PasswordUpdatedAt,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Organization,
		arg.Status,
		arg.IsDeleted,
		arg.DeletedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const deleteUser = `-- name: DeleteUser :execresult
UPDATE USERS SET
    is_deleted = TRUE,
    deleted_at = ?,
    updated_at = ?
WHERE user_id = ?
`

type DeleteUserParams struct {
	DeletedAt sql.NullTime `json:"deleted_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	UserID    uint32       `json:"user_id"`
}

func (q *Queries) DeleteUser(ctx context.Context, arg DeleteUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteUser, arg.DeletedAt, arg.UpdatedAt, arg.UserID)
}

const existsByEmail = `-- name: ExistsByEmail :one
SELECT EXISTS(SELECT 1 FROM USERS WHERE email = ? AND is_deleted = FALSE) as user_exists
`

func (q *Queries) ExistsByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsByEmail, email)
	var user_exists bool
	err := row.Scan(&user_exists)
	return user_exists, err
}

const existsByUsername = `-- name: ExistsByUsername :one
SELECT EXISTS(SELECT 1 FROM USERS WHERE username = ? AND is_deleted = FALSE) as user_exists
`

func (q *Queries) ExistsByUsername(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsByUsername, username)
	var user_exists bool
	err := row.Scan(&user_exists)
	return user_exists, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    user_id, username, password_hash, password_updated_at,
    name, email, phone, organization,
    status, is_deleted, deleted_at, created_at, updated_at
FROM USERS
WHERE email = ? AND is_deleted = FALSE
`

type GetUserByEmailRow struct {
	UserID            uint32         `json:"user_id"`
	Username          string         `json:"username"`
	PasswordHash      string         `json:"password_hash"`
	PasswordUpdatedAt sql.NullTime   `json:"password_updated_at"`
	Name              sql.NullString `json:"name"`
	Email             string         `json:"email"`
	Phone             sql.NullString `json:"phone"`
	Organization      sql.NullString `json:"organization"`
	Status            UsersStatus    `json:"status"`
	IsDeleted         bool           `json:"is_deleted"`
	DeletedAt         sql.NullTime   `json:"deleted_at"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.PasswordHash,
		&i.PasswordUpdatedAt,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Organization,
		&i.Status,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    user_id, username, password_hash, password_updated_at,
    name, email, phone, organization,
    status, is_deleted, deleted_at, created_at, updated_at
FROM USERS
WHERE user_id = ? AND is_deleted = FALSE
`

type GetUserByIDRow struct {
	UserID            uint32         `json:"user_id"`
	Username          string         `json:"username"`
	PasswordHash      string         `json:"password_hash"`
	PasswordUpdatedAt sql.NullTime   `json:"password_updated_at"`
	Name              sql.NullString `json:"name"`
	Email             string         `json:"email"`
	Phone             sql.NullString `json:"phone"`
	Organization      sql.NullString `json:"organization"`
	Status            UsersStatus    `json:"status"`
	IsDeleted         bool           `json:"is_deleted"`
	DeletedAt         sql.NullTime   `json:"deleted_at"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, userID uint32) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, userID)
	var i GetUserByIDRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.PasswordHash,
		&i.PasswordUpdatedAt,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Organization,
		&i.Status,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT
    user_id, username, password_hash, password_updated_at,
    name, email, phone, organization,
    status, is_deleted, deleted_at, created_at, updated_at
FROM USERS
WHERE username = ? AND is_deleted = FALSE
`

type GetUserByUsernameRow struct {
	UserID            uint32         `json:"user_id"`
	Username          string         `json:"username"`
	PasswordHash      string         `json:"password_hash"`
	PasswordUpdatedAt sql.NullTime   `json:"password_updated_at"`
	Name              sql.NullString `json:"name"`
	Email             string         `json:"email"`
	Phone             sql.NullString `json:"phone"`
	Organization      sql.NullString `json:"organization"`
	Status            UsersStatus    `json:"status"`
	IsDeleted         bool           `json:"is_deleted"`
	DeletedAt         sql.NullTime   `json:"deleted_at"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.PasswordHash,
		&i.PasswordUpdatedAt,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Organization,
		&i.Status,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :execresult
UPDATE USERS SET
    password_hash = ?, password_updated_at = ?, name = ?,
    email = ?, phone = ?, organization = ?,
    status = ?, is_deleted = ?, deleted_at = ?, updated_at = ?
WHERE user_id = ?
`

type UpdateUserParams struct {
	PasswordHash      string         `json:"password_hash"`
	PasswordUpdatedAt sql.NullTime   `json:"password_updated_at"`
	Name              sql.NullString `json:"name"`
	Email             string         `json:"email"`
	Phone             sql.NullString `json:"phone"`
	Organization      sql.NullString `json:"organization"`
	Status            UsersStatus    `json:"status"`
	IsDeleted         bool           `json:"is_deleted"`
	DeletedAt         sql.NullTime   `json:"deleted_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
	UserID            uint32         `json:"user_id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUser,
		arg.PasswordHash,
		arg.PasswordUpdatedAt,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Organization,
		arg.Status,
		arg.IsDeleted,
		arg.DeletedAt,
		arg.UpdatedAt,
		arg.UserID,
	)
}
